[package]
name = "databend-common-geobuf"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["geos"]

[lib]
doctest = false
test = true

[dependencies]
borsh = { workspace = true }
databend-common-arrow = { workspace = true }
flatbuffers = "=24.3.25"
flexbuffers = "2.0.0"
geo = { workspace = true }
geo-types = "0.7.13"
geojson = { version = "0.24.1" }
geos = { workspace = true }
geozero = { workspace = true }
ordered-float = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
wkt = { version = "0.10.3" }

[lints]
workspace = true
