[package]
name = "databend-common-exception"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies] # In alphabetical order
databend-common-arrow = { path = "../arrow" }
databend-common-ast = { path = "../../query/ast" }

anyhow = { workspace = true }
arrow-schema = { workspace = true }
backtrace = { git = "https://github.com/rust-lang/backtrace-rs.git", rev = "6145fe6bac65c38375f1216a565a6cc7deb89a2d" }
#backtrace = "0.3.69"
bincode = { workspace = true }
geos = { workspace = true }
geozero = { workspace = true }
http = { workspace = true }
opendal = { workspace = true }
parquet = { workspace = true }
paste = "1.0.9"
prost = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tantivy = { workspace = true }
thiserror = { workspace = true }
tonic = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["geos"]
