[package]
name = "databend-common-exception"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
databend-common-arrow = { workspace = true }
databend-common-ast = { workspace = true }

anyhow = { workspace = true }
arrow-schema = { workspace = true }
backtrace = { workspace = true }
bincode = { workspace = true }
geos = { workspace = true }
geozero = { workspace = true }
http = { workspace = true }
opendal = { workspace = true }
parquet = { workspace = true }
paste = { workspace = true }
prost = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = "0.8"
tantivy = { workspace = true }
thiserror = { workspace = true }
tonic = { workspace = true }
libc = { workspace = true}
gimli = "0.31.0"
object = "0.36.5"
rustc-demangle = "0.1"
once_cell = { workspace = true }
addr2line = "0.24.2"

[package.metadata.cargo-machete]
ignored = ["geos"]

[lints]
workspace = true
