[package]
name = "common-exception"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[features]
vector-index = ["faiss"]

[dependencies] # In alphabetical order
common-arrow = { path = "../arrow" }
common-meta-stoerr = { path = "../../meta/stoerr" }
common-meta-types = { path = "../../meta/types" }

# GitHub dependencies
# TODO: Use the version from crates.io once
# https://github.com/brendanzab/codespan/pull/331 is released.
codespan-reporting = { git = "https://github.com/brendanzab/codespan", rev = "c84116f5" }
faiss = { git = "https://github.com/datafuse-extras/faiss-rs.git", rev = "54d1fe56e8bd3ef74b49455b6da883c1be620c46", features = [
    "static",
], optional = true }

anyhow = { workspace = true }
bincode = { version = "2.0.0-rc.1", features = ["serde", "std", "alloc"] }
http = "0.2"
opendal = { workspace = true }
paste = "1.0.9"
prost = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tonic = { workspace = true }
