[package]
name = "common-fuse-meta"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[features]

[dependencies]
common-arrow = { path = "../../../common/arrow" }
common-base = { path = "../../../common/base" }
common-cache = { path = "../../../common/cache" }
common-config = { path = "../../config" }
common-datablocks = { path = "../../datablocks" }
common-datavalues = { path = "../../datavalues" }
common-exception = { path = "../../../common/exception" }
common-metrics = { path = "../../../common/metrics" }

once_cell = "1.12.0"
serde = { version = "1.0.137", features = ["derive"] }
