[package]
name = "common-dal"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[dependencies]
common-base = { path = "../base" }
common-datablocks = { path = "../datablocks" }
common-exception = { path = "../exception" }
common-infallible = { path = "../infallible" }

async-compat = "0.2.1"
async-trait = "0.1.52"
azure_core = { version = "0.1.0", git = "https://github.com/datafuse-extras/azure-sdk-for-rust.git", rev = "b5bf36b" }
azure_storage = { version = "0.1.0", git = "https://github.com/datafuse-extras/azure-sdk-for-rust.git", rev = "b5bf36b" }
azure_storage_blobs = { version = "0.1.0", git = "https://github.com/datafuse-extras/azure-sdk-for-rust.git", rev = "b5bf36b" }
bytes = "1.1.0"
futures = "0.3.21"
metrics = "0.18.0"
reqwest = "0.11.9"
rusoto_core = "0.47.0"
rusoto_s3 = "0.47.0"
rusoto_sts = "0.47.0"
rusoto_credential = "0.47.0"

[dev-dependencies]
common-metrics = { path = "../metrics" }
rand = "0.8.4"
tempfile = "3.3.0"

[features]
# for unit test only
ut_mock_s3 = []
