[package]
name = "common-dal"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[dependencies]
common-base = {path = "../base"}
common-datablocks = {path = "../datablocks"}
common-exception = {path = "../exception"}
common-cache = {path = "../cache"}
common-infallible = {path = "../infallible"}

async-compat = "0.2.1"
async-trait = "0.1.51"
azure_core_mirror = "0.1.0"
azure_storage_mirror = { version = "0.1.0", features = ["blob"] }
bytes = "1.1.0"
futures = "0.3.18"
metrics = "0.17.0"
reqwest = "0.11.6"
rusoto_core = "0.47.0"
rusoto_s3 = "0.47.0"
rusoto_sts = "0.47.0"
rusoto_credential = "0.47.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.72"

[dev-dependencies]
common-metrics= {path = "../metrics"}
pretty_assertions = "1.0.0"
rand = "0.8.4"
tempfile = "3.2.0"
