[package]
name = "common-storage"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[features]
storage-hdfs = ["opendal/services-hdfs"]

[dependencies]
common-base = { path = "../base" }
common-contexts = { path = "../contexts" }
common-exception = { path = "../exception" }

anyhow = "1.0.65"
backon = "0.2.0"
globiter = "0.1.0"
once_cell = "1.15.0"
opendal = { version = "0.19", features = [
    "layers-retry",
    "layers-tracing",
    "layers-metrics",
    "services-ipfs",
    "services-ftp",
    "compress",
] }
percent-encoding = "2.2.0"
serde = { version = "1.0.145", features = ["derive"] }
