[package]
name = "common-storage"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[features]
storage-hdfs = ["common-meta-app/storage-hdfs"]

[dependencies]
common-arrow = { path = "../arrow" }
common-auth = { path = "../auth" }
common-base = { path = "../base" }
common-exception = { path = "../exception" }
common-expression = { path = "../../query/expression" }
common-meta-app = { path = "../../meta/app" }
common-metrics = { path = "../../metrics" }

anyhow = { workspace = true }
arrow-schema = "45.0.0"
async-backtrace = { workspace = true }
async-trait = "0.1"
bytes = "1"
chrono = { workspace = true }
dashmap = { version = "5.5.1", features = ["serde"] }
flagset = "0.4"
futures = "0.3"
log = { workspace = true }
prometheus_client = { workspace = true }
lazy_static = { workspace = true }
metrics = "0.20.1"
opendal = { workspace = true }
ordered-float = { workspace = true }
parquet = "45.0.0"
regex = "1.8.1"
reqwest = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
