name: 'Test Unite'
description: 'Running unit tests'
inputs:
  github_token:
    description: "Github Token"
    required: true
  codecov_token:
    description: "CodeCov Token"
    required: true
runs:
  using: "composite"
  steps:
    # Workaround for Not Space Left: https://github.com/datafuselabs/databend/issues/3562
    - shell: bash
      run: rm -rf /usr/share/dotnet

    - uses: actions/checkout@v2

    - uses: arduino/setup-protoc@v1
      with:
        version: '3.x'
        repo-token: ${{ inputs.github_token }}

    - uses: actions-rs/toolchain@v1
      with:
        target: ${{ matrix.config.target }}
        components: rustfmt, clippy

    # If you need to reset the cache version, increment the number after `v`
    - uses: Swatinem/rust-cache@v1
      with:
        sharedKey: unit-v1

    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features --no-fail-fast
      env:
        RUST_TEST_THREADS: 2
        RUST_LOG: ERROR
        RUST_BACKTRACE: full
        RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests'
        RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests'

    - name: Install grcov
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: grcov

    - name: Run code coverage
      uses: actions-rs/grcov@v0.1.5
      id: coverage

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1
      with:
        token: ${{ inputs.codecov_token }}
        file: ${{ steps.coverage.outputs.report }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        path: |
          _local_fs/
          _logs/
          _meta/
          metasrv/_logs/
          query/_logs/
          store/_logs/
