[package]
name = "common-config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-base = { path = "../../common/base" }
common-exception = { path = "../../common/exception" }
common-grpc = { path = "../../common/grpc" }
common-hive-meta-store = { path = "../storages/hive-meta-store", optional = true }
common-meta-types = { path = "../../meta/types" }
common-storage = { path = "../../common/storage" }
common-tracing = { path = "../../common/tracing" }
common-users = { path = "../users" }

thrift = { git = "https://github.com/datafuse-extras/thrift", tag = "v0.17.0", optional = true }

clap = { version = "3.2.22", features = ["derive", "env"] }
hex = "0.4.3"
once_cell = "1.15.0"
opendal = { version = "0.19", features = ["layers-retry", "compress"], optional = true }
semver = "1.0.14"
serde = { version = "1.0.145", features = ["derive"] }
serfig = "0.0.2"

[features]
default = []
storage-hdfs = ["opendal/services-hdfs", "common-storage/storage-hdfs"]
hive = ["common-hive-meta-store", "thrift", "storage-hdfs"]
