name: "Upload failure Artifacts"
description: "Upload failure Artifacts"
inputs:
  name:
    description: ""
    required: true
runs:
  using: "composite"
  steps:
    - name: pack failure artifacts
      shell: bash
      run: |
        killall -9 databend-query || true
        killall -9 databend-meta || true

        docker ps -a
        mkdir -p .databend/docker/
        docker ps -a --format "{{.Names}}" | while read -r line; do
            docker logs "$line" > .databend/docker/"$line".log
        done

        tar -zcf target/failure-${{ inputs.name }}.tar.gz \
           nohup.out                                          \
           .databend/                                         \
           src/bendpy/.databend                               \
           src/binaries/.databend                             \
           src/common/arrow/.databend                         \
           src/common/auth/.databend                          \
           src/common/base/.databend                          \
           src/common/building/.databend                      \
           src/common/cache/.databend                         \
           src/common/compress/.databend                      \
           src/common/exception/.databend                     \
           src/common/grpc/.databend                          \
           src/common/hashtable/.databend                     \
           src/common/http/.databend                          \
           src/common/io/.databend                            \
           src/common/license/.databend                       \
           src/common/metrics/.databend                       \
           src/common/openai/.databend                        \
           src/common/storage/.databend                       \
           src/common/tracing/.databend                       \
           src/common/vector/.databend                        \
           src/meta/api/.databend                             \
           src/meta/app/.databend                             \
           src/meta/ee/.databend                              \
           src/meta/embedded/.databend                        \
           src/meta/kvapi/.databend                           \
           src/meta/process/.databend                         \
           src/meta/proto-conv/.databend                      \
           src/meta/protos/.databend                          \
           src/meta/raft-store/.databend                      \
           src/meta/service/.databend                         \
           src/meta/sled-store/.databend                      \
           src/meta/stoerr/.databend                          \
           src/meta/store/.databend                           \
           src/meta/types/.databend                           \
           src/query/ast/.databend                            \
           src/query/catalog/.databend                        \
           src/query/codegen/.databend                        \
           src/query/config/.databend                         \
           src/query/constraint/.databend                     \
           src/query/datavalues/.databend                     \
           src/query/ee/.databend                             \
           src/query/ee-features/aggregating-index/.databend  \
           src/query/ee-features/background-service/.databend \
           src/query/ee-features/data-mask/.databend          \
           src/query/ee-features/table-lock/.databend         \
           src/query/ee-features/vacuum-handler/.databend     \
           src/query/expression/.databend                     \
           src/query/formats/.databend                        \
           src/query/functions/.databend                      \
           src/query/management/.databend                     \
           src/query/pipeline/core/.databend                  \
           src/query/pipeline/sinks/.databend                 \
           src/query/pipeline/sources/.databend               \
           src/query/pipeline/transforms/.databend            \
           src/query/profile/.databend                        \
           src/query/service/.databend                        \
           src/query/settings/.databend                       \
           src/query/sharing/.databend                        \
           src/query/sharing-endpoint/.databend               \
           src/query/sql/.databend                            \
           src/query/storages/common/blocks/.databend         \
           src/query/storages/common/cache/.databend          \
           src/query/storages/common/cache-manager/.databend  \
           src/query/storages/common/index/.databend          \
           src/query/storages/common/pruner/.databend         \
           src/query/storages/common/table-meta/.databend     \
           src/query/storages/factory/.databend               \
           src/query/storages/fuse/.databend                  \
           src/query/storages/hive/hive/.databend             \
           src/query/storages/hive/hive-meta-store/.databend  \
           src/query/storages/iceberg/.databend               \
           src/query/storages/information-schema/.databend    \
           src/query/storages/memory/.databend                \
           src/query/storages/null/.databend                  \
           src/query/storages/parquet/.databend               \
           src/query/storages/random/.databend                \
           src/query/storages/result_cache/.databend          \
           src/query/storages/share/.databend                 \
           src/query/storages/stage/.databend                 \
           src/query/storages/system/.databend                \
           src/query/storages/view/.databend                  \
           src/query/users/.databend                          \
           tests/sqllogictests/.databend                      \

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: target/failure-${{ inputs.name }}.tar.gz
