[package]
name = "common-users"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[features]
io-uring = ["common-meta-store/io-uring"]

[dependencies] # In alphabetical order
# Workspace dependencies
common-base = { path = "../../common/base" }
common-exception = { path = "../../common/exception" }
common-grpc = { path = "../../common/grpc" }
common-management = { path = "../management" }
common-meta-app = { path = "../../meta/app" }
common-meta-kvapi = { path = "../../meta/kvapi" }
common-meta-store = { path = "../../meta/store" }
common-meta-types = { path = "../../meta/types" }

# GitHub dependencies

# Crates.io dependencies
async-backtrace = { workspace = true }
base64 = "0.21"
chrono = { workspace = true }
cidr = { version = "0.2.2" }
enumflags2 = { workspace = true }
jwt-simple = "0.11"
log = { workspace = true }
p256 = "0.13"
parking_lot = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
common-expression = { path = "../expression" }
pretty_assertions = "1.3.0"
wiremock = "0.5.14"
