[package]
name = "common-jsonb"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
byteorder = "1.4.3"
decimal-rs = "0.1.39"
