[package]
name = "databend-common-geo"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
scroll = "0.12.0"

[lints]
workspace = true
