[package]
name = "codegen"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[[bin]]
name = "codegen"
path = "src/bin/codegen.rs"

[dependencies]
common-datavalues = { path = "../datavalues" }
common-expression = { path = "../expression" }

itertools = "0.10"
ordered-float = { version = "3.1.0", features = ["serde"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
