[package]
name = "common-meta-client"
description = "common meta grpc"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false
test = false

[dependencies]
common-arrow = { path = "../../common/arrow" }
common-base = { path = "../../common/base" }
common-exception = { path = "../../common/exception" }
common-grpc = { path = "../../common/grpc" }
common-meta-api = { path = "../api" }
common-meta-app = { path = "../app" }
common-meta-types = { path = "../types" }
common-metrics = { path = "../../common/metrics" }
common-proto-conv = { path = "../proto-conv" }
common-protos = { path = "../protos" }
common-tracing = { path = "../../common/tracing" }

derive_more = "0.99.17"
futures = "0.3.24"
once_cell = "1.15.0"
parking_lot = "0.12.1"
prost = "0.11.0"
rand = "0.8.5"
semver = "1.0.14"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
thiserror = "1"
tonic = { version = "0.8.1", features = ["transport", "codegen", "prost", "tls-roots", "tls"] }
tracing = "0.1.36"

[dev-dependencies]

[build-dependencies]
common-building = { path = "../../common/building" }
