[package]
name = "enterprise"
description = "A real-time Cloud Distributed Query Engine"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies]
# Workspace dependencies
common-base = { path = "../../common/base" }
common-config = { path = "../config" }
common-exception = { path = "../../common/exception" }
common-license = { path = "../../common/license" }

async-backtrace = { workspace = true }

[build-dependencies]
common-building = { path = "../../common/building" }

[package.metadata.cargo-machete]
ignored = ["match-template"]
