header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Datafuse Labs
  paths-ignore:
    # ignore docs and helper tools
    - "scripts"
    - "docker"
    - "docs"
    - "website"
    - "tests"
    - "tools"
    - "benchmark"
    - "src/common/compress/tests"
    # All files under dcl directory should be Databend Community License
    - "src/query/dcl"
    # Ignore hidden files
    - ".cargo"
    - ".databend"
    - ".devcontainer"
    - ".github"
    - ".dockerignore"
    - ".gitignore"
    - ".gitattributes"
    - ".editorconfig"
    # Ignore LICENSE and Makefile
    - "LICENSE"
    - "Makefile"
    # Ignore docs and generated files
    - "**/*.md"
    - "**/*.hbs"
    - "**/*.template"
    - "**/*.cue"
    - "**/*.json"
    - "**/*.sql"
    - "**/*.proto"
    - "**/*.yml"
    - "**/*.yaml"
    - "**/*.toml"
    - "**/*.lock"
    - "**/*.yapf"
    - "**/*.test"

  comment: on-failure
