header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Datafuse Labs
  paths-ignore:
    - "target"
    - "scripts"
    - "docker"
    - "docs"
    - "deploy"
    - "website"
    - "tests"
    - "tools"
    - ".github"
    - ".dockerignore"
    - ".licenserc.yaml"
    - ".gitignore"
    - ".gitattributes"
    - "Cargo.lock"
    - "**/Cargo.toml"
    - "codecov.yml"
    - "CHANGELOG.md"
    - "LICENSE"
    - "Makefile"
    - "README.md"
    - "**/*.md"
    - "**/*.json"
    - "**/*.sql"
    - "rust-toolchain.toml"
    - "rustfmt.toml"
    - "**/*.proto"
    - ".cargo"
    - ".yamllint.yml"
    - ".mergify.yml"

  comment: on-failure
