[workspace]
members = [
    # Common
    "common/allocators",
    "common/arrow",
    "common/building",
    "common/datablocks",
    "common/datavalues",
    "common/flights",
    "common/functions",
    "common/metatypes",
    "common/infallible",
    "common/planners",
    "common/progress",
    "common/runtime",
    "common/streams",
    "common/exception",
    "common/tracing",
    "common/profiling",
    "common/store-api",
    "common/stoppable",
    "common/management",
    "common/io",

    # Datafuse Query
    "query",

    # Datafuse Store
    "store",

    # Datafuse SQL Fuzz
    "query/fuzz",

    # CLI
    "cli"
]

[profile.release]
debug = true

[profile.bench]
debug = true

[profile.dev]
split-debuginfo = "unpacked"
