[package]
name = "fuse-query"
version = "0.1.0"
description = "A Distributed Query Engine"
authors = ["BohuTANG <bohu@datafuse.dev>", "Peter <peter@datafuse.dev>", "Kevin <kevin@datafuse.dev>"]
license = "AGPL-3.0"
include = [
    "benches/*.rs",
    "src/**/*.rs",
    "Cargo.toml",
]
edition = "2018"

[dependencies]
arrow = "2.0"
async-trait = "0.1"
dsn = "1.0"
futures = "0.3"
log = "0.4"
msql-srv = "0.9"
num = "0.3"
num_cpus = "1.0"
paste = "^1.0"
sqlparser = "0.6"
simplelog = "0.8"
thiserror = "1.0"
tokio = { version = "0.3", features = ["macros", "rt", "rt-multi-thread", "stream", "signal"] }

[dev-dependencies]
criterion = "0.3"
pretty_assertions = "0.6"

[[bench]]
name = "bench_main"
harness = false

