[workspace]
members = [
    # Common
    "common/arrow",
    "common/base",
    "common/building",
    "common/cache",
    "common/codegen",
    "common/contexts",
    "common/datablocks",
    "common/datavalues",
    "common/exception",
    "common/functions",
    "common/grpc",
    "common/hive-meta-store",
    "common/io",
    "common/macros",
    "common/management",
    "common/meta/api",
    "common/meta/embedded",
    "common/meta/raft-store",
    "common/meta/sled-store",
    "common/meta/types",
    "common/metrics",
    "common/planners",
    "common/proto-conv",
    "common/protos",
    "common/meta/app",
    "common/streams",
    "common/tracing",

    # Hakari
    "common/workspace-hack",

    # Query
    "query",

    # Meta
    "metasrv",

    # Tools
    "tools/fuzz",
    "tools/metabench",
    "tools/metactl",
]

[profile.release]
debug = 1
lto = "thin"
codegen-units = 1 # Reduce number of codegen units to increase optimizations.

[profile.release.package]
arrow2 = { codegen-units = 4 }
common-functions = { codegen-units = 16 }
databend-query = { codegen-units = 4 }

[profile.bench]
debug = true

[profile.dev]
split-debuginfo = "unpacked"

[profile.dev.package]
addr2line = { opt-level = 3 }
adler = { opt-level = 3 }
gimli = { opt-level = 3 }
miniz_oxide = { opt-level = 3 }
object = { opt-level = 3 }
rustc-demangle = { opt-level = 3 }

[patch.crates-io]
parquet2 = { version = "0.13", optional = true, git = "https://github.com/datafuse-extras/parquet2", branch = "parquet2-0.13-patch2" }
chrono = { git = "https://github.com/datafuse-extras/chrono", rev = "279f590" }
# https://github.com/calder/rust-goldenfile/pull/7
goldenfile = { git = "https://github.com/psiace/rust-goldenfile", rev = "16c5783" }
