[workspace.package]
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[workspace]
resolver = "2"
members = [
    # Binaries
    "src/binaries",
    # Common
    "src/common/arrow",
    "src/common/auth",
    "src/common/base",
    "src/common/building",
    "src/common/cache",
    "src/common/cloud_control",
    "src/common/compress",
    "src/common/exception",
    "src/common/grpc",
    "src/common/hashtable",
    "src/common/http",
    "src/common/io",
    "src/common/metrics",
    "src/common/openai",
    "src/common/tracing",
    "src/common/storage",
    "src/common/vector",
    "src/common/license",
    "src/common/parquet2",
    # Query
    "src/query/ast",
    "src/query/async_functions",
    "src/query/codegen",
    "src/query/config",
    "src/query/constraint",
    "src/query/catalog",
    "src/query/sharing",
    "src/query/sharing_endpoint",
    "src/query/datavalues",
    "src/query/expression",
    "src/query/formats",
    "src/query/functions",
    "src/query/management",
    "src/query/pipeline/core",
    "src/query/pipeline/sinks",
    "src/query/pipeline/sources",
    "src/query/pipeline/transforms",
    "src/query/script",
    "src/query/settings",
    "src/query/sql",
    "src/query/storages/common/blocks",
    "src/query/storages/common/cache",
    "src/query/storages/common/cache_manager",
    "src/query/storages/common/index",
    "src/query/storages/common/io",
    "src/query/storages/common/pruner",
    "src/query/storages/common/table_meta",
    "src/query/storages/delta",
    "src/query/storages/factory",
    "src/query/storages/fuse",
    "src/query/storages/hive/hive",
    "src/query/storages/iceberg",
    "src/query/storages/information_schema",
    "src/query/storages/memory",
    "src/query/storages/null",
    "src/query/storages/random",
    "src/query/storages/share",
    "src/query/storages/stage",
    "src/query/storages/stream",
    "src/query/storages/system",
    "src/query/storages/view",
    "src/query/storages/parquet",
    "src/query/storages/result_cache",
    "src/query/users",
    "src/query/ee_features/vacuum_handler",
    "src/query/ee_features/background_service",
    "src/query/ee_features/aggregating_index",
    "src/query/ee_features/data_mask",
    "src/query/ee_features/storage_encryption",
    "src/query/ee_features/stream_handler",
    "src/query/ee_features/storage_quota",
    # databend-query
    "src/query/service",
    # enterprise
    "src/query/ee",
    # Meta
    "src/meta/api",
    "src/meta/app",
    "src/meta/embedded",
    "src/meta/kvapi",
    "src/meta/process",
    "src/meta/raft-store",
    "src/meta/sled-store",
    "src/meta/stoerr",
    "src/meta/store",
    "src/meta/types",
    "src/meta/ee",
    # meta proto
    "src/meta/proto-conv",
    "src/meta/protos",
    # databend-meta
    "src/meta/service",
    # sqllogictest
    "tests/sqllogictests",
    "src/bendpy",
    # sqlsmith
    "src/tests/sqlsmith",
]

[workspace.dependencies]
# databend maintains
jsonb = { version = "0.4.0" }

opendal = { version = "0.46.0", features = [
    "layers-minitrace",
    "layers-prometheus-client",
    "layers-async-backtrace",
    "services-s3",
    "services-fs",
    "services-gcs",
    "services-cos",
    "services-obs",
    "services-oss",
    "services-azblob",
    "services-azdls",
    "services-ipfs",
    "services-http",
    "services-moka",
    "services-webhdfs",
    "services-huggingface",
] }
sled = { git = "https://github.com/datafuse-extras/sled", tag = "v0.34.7-datafuse.1", default-features = false }

# openraft for debugging
#openraft = { git = "https://github.com/drmingdrmer/openraft", branch = "release-0.9", features = [
openraft = { version = "0.9.9", features = [
    "serde",
    "tracing-log",
    "generic-snapshot-data",
    "storage-v2",
    "loosen-follower-log-revert", # allows removing all data from a follower and restoring from the leader.
] }

# Core crates and utilities
base64 = "0.22"
async-backtrace = "0.2"
async-trait = { version = "0.1.77", package = "async-trait-fn" }
bincode = { version = "2.0.0-rc.3", features = ["serde", "std", "alloc"] }
borsh = { version = "1.2.1", features = ["derive"] }
bytes = "1.5.0"
hashbrown = { version = "0.14.3", default-features = false }
byteorder = "1.4.3"
chrono = { version = "0.4.31", features = ["serde"] }
chrono-tz = { version = "0.8", features = ["serde"] }
clap = { version = "4.4.2", features = ["derive"] }
derive_more = "0.99.17"
enumflags2 = { version = "0.7.7", features = ["serde"] }
ethnum = { version = "1.5.0" }
feature-set = { version = "0.1.1" }
geo = { version = "0.27.0", features = ["use-serde"] }
geos = { version = "8.3", features = ["static", "geo", "geo-types"] }
geozero = { version = "0.13.0", features = ["default", "with-wkb", "with-geos", "with-geojson"] }
itertools = "0.10.5"
match-template = "0.0.1"
mysql_async = { version = "0.34", default-features = false, features = ["rustls-tls"] }
ordered-float = { version = "4.1.0", default-features = false }
poem = { version = "3.0", features = ["rustls", "multipart", "compression"] }
prometheus-client = "0.22"
rand = { version = "0.8.5", features = ["small_rng"] }
regex = "1.8.1"
reqwest = { version = "0.12", default-features = false, features = [
    "json",
    "http2",
    "rustls-tls",
    "rustls-tls-native-roots",
] }
reqwest-hickory-resolver = "0.1"
semver = "1.0.14"
serfig = "0.1.0"
tantivy = "0.22.0"
tokio = { version = "1.35.0", features = ["full"] }
tokio-stream = "0.1.11"
tonic = { version = "0.11.0", features = ["transport", "codegen", "prost", "tls-roots", "tls"] }
tonic-reflection = { version = "0.11.0" }
typetag = "0.2.3"
uuid = { version = "1.1.2", features = ["serde", "v4"] }
walkdir = "2.3.2"
derive-visitor = "0.3.0"
http = "1"
criterion = "0.5"

# Synchronization
dashmap = "5.4.0"
once_cell = "1.15.0"
ordq = "0.2.0"
parking_lot = "0.12.1"

# Future and async
futures = "0.3.24"
futures-async-stream = { version = "0.2.7" }
futures-util = "0.3.24"
stream-more = "0.1.3"

# Error handling
anyerror = { version = "=0.1.10" }
anyhow = { version = "1.0.65" }
thiserror = { version = "1" }

# Crates from arrow-rs
arrow = { version = "51" }
arrow-array = { version = "51" }
arrow-buffer = { version = "51" }
arrow-cast = { version = "51", features = ["prettyprint"] }
arrow-data = { version = "51" }
arrow-flight = { version = "51", features = ["flight-sql-experimental", "tls"] }
arrow-format = { version = "0.8.1", features = ["flight-data", "flight-service", "ipc"] }
arrow-ipc = { version = "51" }
arrow-ord = { version = "51" }
arrow-schema = { version = "51", features = ["serde"] }
arrow-select = { version = "51" }
parquet = { version = "51", features = ["async"] }
parquet_rs = { package = "parquet", version = "51" }
# Must use the same version with arrow-ipc
flatbuffers = { version = "23" }

# Crates from risingwavelabs
arrow-udf-js = { package = "arrow-udf-js", git = "https://github.com/datafuse-extras/arrow-udf", rev = "d0a21f0" }
arrow-udf-wasm = { package = "arrow-udf-wasm", git = "https://github.com/datafuse-extras/arrow-udf", rev = "d0a21f0" }

# Serialization
prost = { version = "0.12.1" }
prost-build = { version = "0.12.1" }
serde = { version = "1.0.164", features = ["derive", "rc"] }
serde_with = { version = "3.8.1" }
serde_json = { version = "1.0.85", default-features = false, features = ["preserve_order"] }
tonic-build = { version = "0.11" }

# Memory management
bumpalo = "3.12.0"
tikv-jemalloc-ctl = { version = "0.5.0", features = ["use_std"] }

# Observability
log = { version = "0.4.21", features = ["serde", "kv_unstable_std"] }
logcall = "0.1.5"
minitrace = { version = "0.6.5", features = ["enable"] }
minitrace-opentelemetry = "0.6.5"
opentelemetry = { version = "0.22", features = ["trace", "logs"] }
opentelemetry-otlp = { version = "0.15", features = [
    "trace",
    "logs",
    "grpc-tonic",
    "http-proto",
    "reqwest-client",
] }
opentelemetry_sdk = { version = "0.22", features = ["trace", "logs", "rt-tokio"] }
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json", "valuable"] }

[profile.release]
debug = 1
lto = "thin"
overflow-checks = false
incremental = false
opt-level = "s"
# codegen-units = 1 # Reduce number of codegen units to increase optimizations.

# [profile.release.package]
# arrow2 = { codegen-units = 4 }
# common-functions = { codegen-units = 16 }
# databend-query = { codegen-units = 4 }
# databend-binaries = { codegen-units = 4 }

[profile.bench]
debug = true
overflow-checks = false

[profile.dev]
split-debuginfo = "unpacked"
overflow-checks = false
# wait until https://github.com/rust-lang/rust/issues/100142 fixed
incremental = false

[profile.dev.package]
addr2line = { opt-level = 3 }
adler = { opt-level = 3 }
gimli = { opt-level = 3 }
miniz_oxide = { opt-level = 3 }
object = { opt-level = 3 }
rustc-demangle = { opt-level = 3 }

[profile.test]
opt-level = 0
debug = true
codegen-units = 16
lto = false
debug-assertions = true
overflow-checks = true
rpath = false

[patch.crates-io]
arrow-format = { git = "https://github.com/Xuanwo/arrow-format", rev = "be633a0" }
icelake = { git = "https://github.com/icelake-io/icelake", rev = "be8b2c2" }
ethnum = { git = "https://github.com/ariesdevil/ethnum-rs", rev = "4cb05f1" }
async-backtrace = { git = "https://github.com/zhang2014/async-backtrace.git", rev = "dea4553" }
z3 = { git = "https://github.com/prove-rs/z3.rs", rev = "247d308" }
z3-sys = { git = "https://github.com/prove-rs/z3.rs", rev = "247d308" }
# proj = { git = "https://github.com/ariesdevil/proj", rev = "51e1c60" }
derive-visitor = { git = 'https://github.com/andylokandy/derive-visitor.git', rev = "c07c6b6" }
