[package]
name = "common-storages-parquet"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-arrow = { path = "../../../common/arrow" }
common-base = { path = "../../../common/base" }
common-catalog = { path = "../../catalog" }
common-exception = { path = "../../../common/exception" }
common-expression = { path = "../../expression" }
common-functions = { path = "../../functions" }
common-meta-app = { path = "../../../meta/app" }
common-pipeline-core = { path = "../../pipeline/core" }
common-pipeline-sources = { path = "../../pipeline/sources" }
common-storage = { path = "../../../common/storage" }
storages-common-index = { path = "../common/index" }
storages-common-pruner = { path = "../common/pruner" }
storages-common-table-meta = { path = "../common/table-meta" }

arrow-array = "45.0.0"
arrow-schema = "45.0.0"
async-backtrace = { workspace = true }
async-trait = { version = "0.1.57", package = "async-trait-fn" }
chrono = { workspace = true }
futures = "0.3.24"
log = { workspace = true }
opendal = { workspace = true }
parquet = { version = "45.0.0", features = ["async"] }
serde = { workspace = true }
typetag = "0.2.3"

[dev-dependencies]
common-sql = { path = "../../sql" }
