[package]
name = "databend-common-storages-orc"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = true

[dependencies]
databend-common-catalog = { path = "../../catalog" }
databend-common-exception = { path = "../../../common/exception" }
databend-common-expression = { path = "../../expression" }
databend-common-meta-app = { path = "../../../meta/app" }
databend-common-pipeline-core = { path = "../../pipeline/core" }
databend-common-pipeline-sources = { path = "../../pipeline/sources" }
databend-common-storage = { path = "../../../common/storage" }
databend-storages-common-table-meta = { path = "../common/table_meta" }

arrow-array = { workspace = true }
arrow-schema = { workspace = true }
async-backtrace = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
opendal = { workspace = true, features = ["layers-blocking"]}
orc-rust = { git = "https://github.com/datafusion-contrib/datafusion-orc", rev = "ac5a8ab" }
serde = { workspace = true }
typetag = { workspace = true }
