[package]
name = "bendpy"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "databend"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.18.1"
pyo3-asyncio = { version = "0.14", features = ["attributes", "tokio-runtime"] }
# Workspace dependencies
common-config = { path = "../query/config" }
common-exception = { path = "../common/exception" }
common-expression = { path = "../query/expression" }
common-functions = { path = "../query/functions" }
common-meta-app = { path = "../meta/app" }
common-storage = { path = "../common/storage" }
databend-query = { path = "../query/service" }

# # Crates.io dependencies
# comfy-table = "6.1.3"
# opendal = { workspace = true }
# serde = { workspace = true }
tokio = { version = "1.24", features = ["macros", "rt", "rt-multi-thread", "sync"] }
tokio-stream = "0.1.10"
