[package]
name = "bendpy"
version = "0.0.0"
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[build-dependencies]
pyo3-build-config = "0.18.3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "databend"
crate-type = ["cdylib"]

[features]
default = []
abi =  ["pyo3/extension-module", "pyo3/abi3", "pyo3/abi3-py37" ]

[dependencies]
arrow = { workspace = true, features = ["pyarrow"] }
arrow-schema = { workspace = true }
ctor = "0.2.5"
databend-common-config = { workspace = true }
databend-common-exception = { workspace = true }
databend-common-expression = { workspace = true }
databend-common-license = { workspace = true }
databend-common-meta-app = { workspace = true }
databend-common-meta-embedded = { workspace = true }
databend-common-users = { workspace = true }
databend-query = { workspace = true, features = [
    "simd",
    "disable_initial_exec_tls",
]}
pyo3 = { version = "0.21.2" }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread", "sync"] }
tokio-stream = { workspace = true }
uuid = { workspace = true }

[lints]
workspace = true
