[package]
name = "databend-query-enterprise"
description = "databend command line tools"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[features]
default = ["simd", "jemalloc", "databend-enterprise"]
memory-profiling = ["databend-query/memory-profiling", "common-base/memory-profiling"]
simd = ["databend-query/simd"]
jemalloc = ["common-base/jemalloc"]
tokio-console = [
    "databend-query/io-uring",
    "common-base/tracing",
    "common-tracing/console",
]
io-uring = [
    "databend-query/io-uring",
]

enable-histogram-metrics = [
    "default",
    "common-metrics/enable-histogram",
    "databend-query/enable-histogram-metrics",
]

# Enable databend enterprise features
databend-enterprise = []

[dependencies]
# Workspace dependencies
common-base = { path = "../../common/base" }
common-config = { path = "../../query/config" }
common-exception = { path = "../../common/exception" }
common-expression = { path = "../../query/expression" }
common-meta-client = { path = "../../meta/client" }
common-metrics = { path = "../../common/metrics" }
common-tracing = { path = "../../common/tracing" }
databend-query = { path = "../../query/service" }

# Crates.io dependencies
async-backtrace = { workspace = true }
comfy-table = "6.1.3"
limits-rs = "0.2.0"
sentry = { version = "0.30", default-features = false, features = [
    "backtrace",
    "contexts",
    "panic",
    "reqwest",
    "rustls",
] }
tokio-stream = "0.1.10"
tracing = "0.1.36"

[[bin]]
name = "databend-query-enterprise"
path = "../query/main.rs"
doctest = false
test = false
