[package]
name = "common-storages-index"
version = "0.1.0"
edition = "2021"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-catalog = { path = "../../catalog" }
common-datablocks = { path = "../../datablocks" }
common-datavalues = { path = "../../datavalues" }
common-exception = { path = "../../../common/exception" }
common-functions = { path = "../../functions" }
common-fuse-meta = { path = "../fuse-meta" }
common-legacy-expression = { path = "../../legacy-expression" }
common-pipeline-transforms = { path = "../../pipeline/transforms" }

xorfilter-rs = { git = "https://github.com/datafuse-extras/xorfilter", features = ["cbordata"] }

anyerror = "=0.1.7"
cbordata = { version = "0.6.0" }
serde = { version = "1.0.145", features = ["derive"] }
thiserror = "1"
tracing = "0.1.36"

[dev-dependencies]
rand = "0.8.5"
