[package]
name = "common-storages-memory"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-base = { path = "../../../common/base" }
common-catalog = { path = "../../catalog" }
common-exception = { path = "../../../common/exception" }
common-expression = { path = "../../expression" }
common-meta-app = { path = "../../../meta/app" }
common-pipeline-core = { path = "../../pipeline/core" }
common-pipeline-sinks = { path = "../../pipeline/sinks" }
common-pipeline-sources = { path = "../../pipeline/sources" }
common-storage = { path = "../../../common/storage" }
storages-common-table-meta = { path = "../common/table_meta" }

async-backtrace = { workspace = true }
async-trait = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }
typetag = { workspace = true }

[build-dependencies]
common-building = { path = "../../../common/building" }
