name: "Build MacOS"
description: "Build in MacOS"
inputs:
  target:
    description: ""
    required: true
runs:
  using: "composite"
  steps:
    - name: Rust setup
      shell: bash
      run: |
        bash ./scripts/setup/dev_setup.sh -yb
        rustup target add ${{ inputs.target }}

    - name: Build Debug
      if: env.BUILD_PROFILE == 'debug'
      shell: bash
      run: cargo build --target ${{ inputs.target }}

    - name: Build Release
      if: env.BUILD_PROFILE == 'release'
      shell: bash
      run: cargo build --target ${{ inputs.target }} --release

    - name: Upload artifact
      uses: ./.github/actions/artifact_upload
      with:
        sha: ${{ github.sha }}
        target: ${{ inputs.target }}
