name: "Build Linux"
description: "Build with profile"
inputs:
  target:
    description: ""
    required: true
  upload:
    description: "Upload artifact"
    required: false
    default: "true"
  artifacts:
    description: "Artifacts to build"
    required: false
    default: "sqllogictests,meta,query"
  features:
    description: "Features to build"
    required: false
    default: "default"
runs:
  using: "composite"
  steps:
    - name: Setup Build Tool
      uses: ./.github/actions/setup_build_tool
      with:
        target: ${{ inputs.target }}
        bypass_env_vars: RUSTFLAGS,RUST_LOG

    # build all binaries for debug
    - name: Build Debug
      if: env.BUILD_PROFILE == 'debug' && inputs.artifacts == 'all'
      shell: bash
      run: cargo build --target ${{ inputs.target }} --features ${{ inputs.features }}

    - name: Build Debug for specific artifacts
      if: env.BUILD_PROFILE == 'debug' && inputs.artifacts != 'all'
      shell: bash
      run: |
        artifacts="${{ inputs.artifacts }}"
        echo "==> building libs ..."
        cargo build --target ${{ inputs.target }} --features ${{ inputs.features }} --lib
        for artifact in ${artifacts//,/ }; do
          echo "==> building databend-$artifact ..."
          cargo build --target ${{ inputs.target }} --features ${{ inputs.features }} --bin databend-$artifact
        done

    - name: Set Release build flags
      if: env.BUILD_PROFILE == 'release'
      shell: bash
      run: |
        case ${{ inputs.target }} in
          x86_64-unknown-linux-gnu)
            flags="-C target-feature=+sse4.2"
            ;;
          x86_64-unknown-linux-musl)
            flags="-C target-feature=+sse4.2 -C link-arg=-Wl,--compress-debug-sections=zlib-gabi"
            ;;
          aarch64-unknown-linux-gnu)
            flags=""
            ;;
          aarch64-unknown-linux-musl)
            flags="-C link-arg=-Wl,--compress-debug-sections=zlib-gabi"
            ;;
          *)
            flags=""
            ;;
        esac
        echo "RUSTFLAGS=${flags}" >> $GITHUB_ENV
        target=${{ inputs.target }}
        echo "BUILD_ARCH=${target/-unknown-linux-*}" >> $GITHUB_ENV

    - name: Build Release
      if: env.BUILD_PROFILE == 'release'
      shell: bash
      run: |
        artifacts="${{ inputs.artifacts }}"
        echo "==> building libs ..."
        cargo build --target ${{ inputs.target }} --features ${{ inputs.features }} --release --lib
        for artifact in ${artifacts//,/ }; do
          echo "==> building databend-$artifact ..."
          cargo build --target ${{ inputs.target }} --features ${{ inputs.features }} --release --bin databend-$artifact
        done

    - shell: bash
      run: readelf -p .comment ./target/${{ inputs.target }}/${{ env.BUILD_PROFILE }}/databend-query

    - name: Copyobj zlib for gnu binaries
      if: env.BUILD_PROFILE == 'release' && endsWith(inputs.target, '-gnu')
      shell: bash
      run: |
        artifacts="${{ inputs.artifacts }}"
        for artifact in ${artifacts//,/ }; do
          echo "==> compressing zlib debug for databend-$artifact ..."
          build-tool /usr/bin/${{ env.BUILD_ARCH }}-linux-gnu-objcopy --compress-debug-sections=zlib-gnu ./target/${{ inputs.target }}/release/databend-$artifact
        done

    - name: Upload artifact
      if: inputs.upload == 'true'
      uses: ./.github/actions/artifact_upload
      with:
        sha: ${{ github.sha }}
        target: ${{ inputs.target }}
        category: ${{ inputs.features }}
