[package]
name = "databend-storages-common-txn"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[dependencies]
chrono = { workspace = true }
databend-common-meta-app = { workspace = true }
databend-common-meta-types = { workspace = true }
databend-storages-common-table-meta = { workspace = true }
parking_lot = { workspace = true }
serde = { version = "1.0.194", features = ["derive"] }
uuid = { workspace = true }

[lints]
workspace = true
