[package]
name = "databend-common-profile"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies]
databend-common-base = { path = "../../common/base" }

dashmap = { workspace = true }
