[package]
name = "common-meta-sled-store"
description = "Sled store backend for raft state machine"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[features]
io-uring = ["sled/io_uring"]

[dependencies]
common-meta-types = { path = "../types" }

openraft = { git = "https://github.com/drmingdrmer/openraft", tag = "v0.7.4-alpha.2" }
sled = { git = "https://github.com/datafuse-extras/sled", tag = "v0.34.7-datafuse.1", default-features = false }

anyhow = "1.0.65"
byteorder = "1.4.3"
once_cell = "1.15.0"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
tempfile = "3.3.0"
tracing = "0.1.36"

[dev-dependencies]
common-base = { path = "../../common/base" }
common-tracing = { path = "../../common/tracing" }
