[package]
name = "background-service"
description = "background service to run automatic optimization for databend cluster"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies]
# Workspace dependencies
common-base = { path = "../../../common/base" }
common-exception = { path = "../../../common/exception" }
common-meta-app = { path = "../../../meta/app" }

arrow-array = { workspace = true }
async-backtrace = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }

[build-dependencies]
