[package]
name = "common-legacy-expression"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies]
common-datavalues = { path = "../datavalues" }
common-exception = { path = "../../common/exception" }
common-functions = { path = "../functions" }

once_cell = "1.15"
serde = { version = "1", features = ["derive"] }
