[package]
name = "common-pipeline-sources"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[package.metadata.cargo-machete]
ignored = ["xml-rs"]

[dependencies]
async-backtrace = { workspace = true }
async-channel = "1.7.1"
common-arrow = { path = "../../../common/arrow" }
common-base = { path = "../../../common/base" }
common-catalog = { path = "../../catalog" }
common-compress = { path = "../../../common/compress" }
common-exception = { path = "../../../common/exception" }
common-expression = { path = "../../expression" }
common-formats = { path = "../../formats" }
common-io = { path = "../../../common/io" }
common-meta-app = { path = "../../../meta/app" }
common-pipeline-core = { path = "../core" }
common-settings = { path = "../../settings" }
common-storage = { path = "../../../common/storage" }

async-trait = { workspace = true }
bstr = "1.0.1"
csv-core = "0.1.10"
dashmap = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }

log = { workspace = true }
minitrace = { workspace = true }
opendal = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

typetag = { workspace = true }
xml-rs = "0.8.14"
