# Usage:
# datafuse-query -c datafuse_query_config_spec.toml

# Log level.
log_level = "ERROR"

# DatafuseQuery rpc address.
# For flight rpc.
flight_api_address = "0.0.0.0:9093"

# DatafuseQuery http address.
# For admin RESET API.
http_api_address = "0.0.0.0:8083"

# DatafuseQuery metrics RESET API.
metric_api_address = "0.0.0.0:7073"

# MySQL Handler.
mysql_handler_host = "0.0.0.0"
mysql_handler_port = 3309

# ClickHouse Handler.
clickhouse_handler_host = "0.0.0.0"
clickhouse_handler_port = 9003
