[package]
name = "databend-enterprise-meta"
description = "enterprise features for databend-meta"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
anyhow = { workspace = true }
databend-common-base = { workspace = true }
databend-common-license = { workspace = true }
jwt-simple = { workspace = true }
log = { workspace = true }

[build-dependencies]
databend-common-building = { workspace = true }

[lints]
workspace = true
