[package]
name = "common-datavalues"
version = "0.1.0"
authors = ["Datafuse Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies] # In alphabetical order
# Workspace dependencies
common-arrow = {path = "../arrow"}
common-exception = {path = "../exception"}

# Github dependencies

# Crates.io dependencies
anyhow = "1.0.41"
paste = "^1.0"
num = "^0.4"
unsafe_unwrap = "^0.1.0"
ordered-float = "2.6"
serde = { version = "1.0", features = ["derive"] }
ahash = "0.7.4"
prettytable-rs = { version = "0.8.0"}


[dev-dependencies]
pretty_assertions = "0.7"
