[package]
name = "databend-common-column"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }


[lib]
doctest = false
test = true

[features]
default = ["column-default"]
serde_types = ["serde", "serde_derive"]
simd = []

column-default = [
    "serde_types",
    "simd",
]

[dependencies]

databend-common-exception = { workspace = true }
databend-common-base = { workspace = true }

serde = { workspace = true, features = ["rc"], optional = true }
serde_derive = { workspace = true, optional = true }
foreign_vec = { workspace = true }
match-template = { workspace = true }
bytemuck = { workspace = true }
num-traits = { workspace = true }
enum-as-inner = { workspace = true }
arrow-buffer = { workspace = true }
arrow-schema = { workspace = true }
hex = { workspace = true }
arrow-data = { workspace = true }
ethnum =  { workspace = true }
simdutf8 = { workspace = true }
either = { workspace = true }
serde_json  = { workspace = true }


[dev-dependencies]
proptest = {workspace = true}

[lints]
workspace = true
