[package]
name = "databend-common-storages-hive"
version = "0.1.0"
edition = "2021"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false

[lib]
doctest = false
test = true

[dependencies]
async-backtrace = { workspace = true }
async-recursion = "1.1.1"
async-trait = { workspace = true }
chrono = { workspace = true }
databend-common-base = { workspace = true }
databend-common-catalog = { workspace = true }
databend-common-config = { workspace = true }
databend-common-exception = { workspace = true }
databend-common-expression = { workspace = true }
databend-storages-common-pruner = { workspace = true }
databend-common-functions = { workspace = true }
databend-common-meta-app = { workspace = true }
databend-common-meta-store = { workspace = true }
databend-common-meta-types = { workspace = true }
databend-common-pipeline-core = { workspace = true }
databend-common-pipeline-sources = { workspace = true }
databend-common-sql = { workspace = true }
databend-common-storage = { workspace = true }
databend-common-storages-parquet = { workspace = true }
databend-storages-common-table-meta = { workspace = true }
fastrace = { workspace = true }
faststr = "0.2"
parquet = {workspace = true}
futures = { workspace = true }
hive_metastore = "0.1.0"
log = { workspace = true }
opendal = { workspace = true }
recursive = "0.1.1"
serde = { workspace = true }
typetag = { workspace = true }
volo-thrift = "0.10"

[lints]
workspace = true
