[package]
name = "common-meta-store"
version = "0.1.0"
description = "MetaStore is impl with either a local embedded meta store, or a grpc-client of metasrv"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[features]
io-uring = ["common-meta-embedded/io-uring"]

[dependencies]
# Workspace dependencies
common-grpc = { path = "../../common/grpc" }
common-meta-api = { path = "../api" }
common-meta-client = { path = "../client" }
common-meta-embedded = { path = "../embedded" }
common-meta-types = { path = "../types" }

# Crates.io dependencies
async-trait = "0.1.56"
tracing = "0.1.35"
