cargo-features = ["edition2021"]

[package]
name = "common-metatypes"
version = "0.1.0"
authors = ["Datafuse Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"

[dev-dependencies]
pretty_assertions = "0.7"
