[package]
name = "common-datablocks"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies] # In alphabetical order
# Workspace dependencies
common-arrow = { path = "../../common/arrow" }
common-datavalues = { path = "../datavalues" }
common-exception = { path = "../../common/exception" }
common-io = { path = "../../common/io" }

# Github dependencies

# Crates.io dependencies
ahash = "0.8.0"
comfy-table = "6.1.0"
parking_lot = "0.12.1"
primitive-types = "0.12.0"
regex = "1.6.0"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"

[dev-dependencies]
pretty_assertions = "1.3.0"
