[package]
name = "background-service"
description = "background service to run automatic optimization for databend cluster"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies]
# Workspace dependencies
arrow-array = { version = "37.0.0" }
async-backtrace = { workspace = true }
async-trait = "0.1.57"
common-meta-app = { path = "../../../meta/app" }
common-base = { path = "../../../common/base" }
common-exception = { path = "../../../common/exception" }

[build-dependencies]

[package.metadata.cargo-machete]
ignored = ["match-template"]
