[package]
name = "common-protos"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[dependencies]
prost = "0.10.1"
tonic = { version = "=0.6.2", features = ["transport", "codegen", "prost", "tls-roots", "tls"] }

[build-dependencies]
prost-build = "0.10.1"
tonic-build = "0.7.0"

[dev-dependencies]
