[package]
name = "common-io"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common-exception= {path = "../exception"}
bytes = "1.1.0"

[dev-dependencies]
rand = "0.8.4"
