[package]
name = "common-meta-raft-store"
description = "Raft state machine"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[features]
io-uring = ["common-meta-sled-store/io-uring"]

[dependencies]
common-exception = { path = "../../common/exception" }
common-grpc = { path = "../../common/grpc" }
common-io = { path = "../../common/io" }
common-meta-api = { path = "../api" }
common-meta-sled-store = { path = "../sled-store" }
common-meta-types = { path = "../types" }
common-tracing = { path = "../../common/tracing" }

# crates.io deps
anyhow = "1.0.65"
async-trait = "0.1.57"
bytes = "1.2.1"
derive_more = "0.99.17"
hostname = "0.3.1"
maplit = "1.0.2"
num = "0.4.0"
once_cell = "1.15.0"
rand = "0.8.5"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
tracing = "0.1.36"

[dev-dependencies]
common-base = { path = "../../common/base" }
pretty_assertions = "1.3.0"
tempfile = "3.3.0"
