[package]
name = "storages-common-locks"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies]
common-base = { path = "../../../../common/base" }
common-catalog = { path = "../../../catalog" }
common-exception = { path = "../../../../common/exception" }
common-meta-app = { path = "../../../../meta/app" }
common-meta-kvapi = { path = "../../../../meta/kvapi" }
common-meta-types = { path = "../../../../meta/types" }
common-metrics = { path = "../../../../common/metrics" }
common-pipeline-core = { path = "../../../pipeline/core" }
common-users = { path = "../../../users" }

async-backtrace = { workspace = true }
async-channel = "1.7.1"
async-trait = "0.1.57"
chrono = { workspace = true }
futures = "0.3.24"
futures-util = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
parking_lot = "0.12.1"
rand = "0.8.5"
