cargo-features = ["edition2021"]

[package]
name = "common-stoppable"
version = "0.1.0"
authors = ["Datafuse Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies] # In alphabetical order
# Workspace dependencies
common-exception = {path = "../exception"}
common-runtime = {path = "../runtime"}
common-tracing = {path = "../tracing"}

# Github dependencies

# Crates.io dependencies
async-trait = "0.1"
ctrlc = { version = "3.1.9", features = ["termination"] }
futures = "0.3"

[dev-dependencies]
