[package]
name = "common-legacy-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-ast = { path = "../ast" }
common-datavalues = { path = "../datavalues" }
common-exception = { path = "../../common/exception" }
common-legacy-planners = { path = "../legacy-planners" }

async-trait = "0.1.56"
sqlparser = { git = "https://github.com/datafuse-extras/sqlparser-rs", rev = "7f246e3" }
