[package]
name = "common-storages-system"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-ast = { path = "../../ast" }
common-base = { path = "../../../common/base" }
common-catalog = { path = "../../catalog" }
common-cloud-control = { path = "../../../common/cloud_control" }
common-config = { path = "../../config" }
common-exception = { path = "../../../common/exception" }
common-expression = { path = "../../expression" }
common-functions = { path = "../../functions" }
common-meta-api = { path = "../../../meta/api" }
common-meta-app = { path = "../../../meta/app" }
common-meta-types = { path = "../../../meta/types" }
common-metrics = { path = "../../../common/metrics" }
common-pipeline-core = { path = "../../pipeline/core" }
common-pipeline-sources = { path = "../../pipeline/sources" }
common-profile = { path = "../../profile" }
common-sql = { path = "../../sql" }
common-storage = { path = "../../../common/storage" }
common-storages-fuse = { path = "../fuse" }
common-storages-result-cache = { path = "../result_cache" }
common-storages-stream = { path = "../stream" }
common-storages-view = { path = "../view" }
common-users = { path = "../../users" }
jsonb = { workspace = true }
storages-common-cache = { path = "../common/cache" }
storages-common-cache-manager = { path = "../common/cache_manager" }

async-backtrace = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
once_cell = { workspace = true }
opendal = { workspace = true }
parking_lot = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_repr = "0.1.9"
snailquote = "0.3.1"
tikv-jemalloc-ctl = { workspace = true }

typetag = { workspace = true }
walkdir = { workspace = true }

[build-dependencies]
common-building = { path = "../../../common/building" }
