[package]
name = "common-storages-share"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-exception = { path = "../../../common/exception" }
common-meta-app = { path = "../../../meta/app" }
common-storages-util = { path = "../util" }

opendal = { version = "0.19", features = ["layers-retry"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"

[dev-dependencies]
goldenfile = "1.4"
tempfile = "3.3.0"
