[package]
name = "common-catalog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-base = { path = "../../common/base" }
common-config = { path = "../config" }
common-contexts = { path = "../../common/contexts" }
common-datablocks = { path = "../datablocks" }
common-datavalues = { path = "../datavalues" }
common-exception = { path = "../../common/exception" }
common-functions = { path = "../functions" }
common-io = { path = "../../common/io" }
common-legacy-expression = { path = "../legacy-expression" }
common-legacy-planners = { path = "../legacy-planners" }
common-meta-app = { path = "../../meta/app" }
common-meta-types = { path = "../../meta/types" }
common-pipeline-core = { path = "../pipeline/core" }
common-settings = { path = "../settings" }
common-storage = { path = "../../common/storage" }

async-trait = "0.1.57"
dyn-clone = "1.0.9"
opendal = { version = "0.19", features = ["layers-retry"] }
