[package]
name = "common-meta-types"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies]
common-exception = { path = "../../common/exception" }
common-storage = { path = "../../common/storage" }

openraft = { git = "https://github.com/drmingdrmer/openraft", tag = "v0.7.4-alpha.2" }
sled = { git = "https://github.com/datafuse-extras/sled", tag = "v0.34.7-datafuse.1", default-features = false }

anyerror = "=0.1.7"
chrono = "0.4.22"
derive_more = "0.99.17"
enumflags2 = { version = "0.7.5", features = ["serde"] }
hex = "0.4.3"
maplit = "1.0.2"
num-derive = "0.3.3"
num-traits = "0.2.15"
once_cell = "1.15.0"
prost = "0.11.0"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
sha1 = "0.10.5"
sha2 = "0.10.6"
thiserror = "1"
tonic = { version = "0.8.1", features = ["transport", "codegen", "prost", "tls-roots", "tls"] }

[build-dependencies]
common-building = { path = "../../common/building" }
prost-build = "0.11.1"
tonic-build = "0.8.0"

[dev-dependencies]
anyhow = "1.0.65"
regex = "1.6.0"
