[package]
name = "common-storages-stream"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-base = { path = "../../../common/base" }
common-catalog = { path = "../../catalog" }
common-exception = { path = "../../../common/exception" }
common-expression = { path = "../../expression" }
common-meta-app = { path = "../../../meta/app" }
common-metrics = { path = "../../../common/metrics" }
common-pipeline-core = { path = "../../pipeline/core" }
common-pipeline-sources = { path = "../../pipeline/sources" }
common-sql = { path = "../../sql" }
common-storages-fuse = { path = "../fuse" }

storages-common-pruner = { path = "../common/pruner" }
storages-common-table-meta = { path = "../common/table_meta" }

async-backtrace = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
log = { workspace = true }
minitrace = { workspace = true }
opendal = { workspace = true }

[build-dependencies]
