[package]
name = "databend-common-io"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
bincode = { workspace = true }
borsh = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
databend-common-base = { workspace = true }
databend-common-exception = { workspace = true }
enquote = { workspace = true }
enumflags2 = { workspace = true }
ethnum = { workspace = true }
geo = { workspace = true }
geos = { workspace = true }
geozero = { workspace = true }
jiff = { workspace = true }
lexical-core = { workspace = true }
micromarshal = { workspace = true }
roaring = { workspace = true, features = ["serde"] }
scroll = { workspace = true }
serde = { workspace = true }
wkt = { workspace = true }

[dev-dependencies]
aho-corasick = { workspace = true }
rand = { workspace = true }
rmp-serde = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["geos"]

[lints]
workspace = true
