[package]
name = "databend-common-pipeline-core"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = true

[dependencies]
databend-common-base = { path = "../../../common/base" }
databend-common-exception = { path = "../../../common/exception" }
databend-common-expression = { path = "../../expression" }

async-backtrace = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
minitrace = { workspace = true }
petgraph = "0.6.2"
serde = { workspace = true }
log = "0.4.21"

[dev-dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
typetag = { workspace = true }
