[package]
name = "common-pipeline-core"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-datablocks = { path = "../../datablocks" }
common-datavalues = { path = "../../datavalues" }
common-exception = { path = "../../../common/exception" }
common-io = { path = "../../../common/io" }

async-trait = "0.1.57"
futures = "0.3.24"
futures-util = "0.3.24"
itertools = "0.10.5"
num_cpus = "1.13.1"
once_cell = "1.15.0"
parking_lot = "0.12.1"
petgraph = "0.6.2"
serde = { version = "1.0.145", features = ["derive"] }
time = "0.3.14"

[dev-dependencies]
tokio = { version = "1.21.1", features = ["full"] }
