name: 'Test Unite Ubuntu'
description: 'Running unit tests'
inputs:
  github_token:
    description: "Github Token"
    required: true
  codecov_token:
    description: "CodeCov Token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Maximize build space
      uses: ./.github/actions/cleanup
    - name: pull dev container on need
      shell: bash
      run: |
        mkdir -p /tmp/dev_container
        if [[ -e /tmp/dev_container/dev-container.tar ]]; then
          echo "found dev container cache "
          docker load -i /tmp/dev_container/dev-container.tar
        else
          echo "dev container cache not found"
        fi
        docker pull datafuselabs/dev-container:latest
        echo "cache latest image"
        mkdir -p /tmp/dev_container
        docker save datafuselabs/dev-container:latest > /tmp/dev_container/dev-container.tar
    - name: unit test
      shell: bash
      run: |
        echo "running unit tests"
        ./scripts/setup/run_docker.sh bash -c export RUSTFLAGS=${RUSTFLAGS} && export RUSTDOCFLAGS=${RUSTDOCFLAGS} && \
        export RUST_LOG=${RUST_LOG} && export RUST_BACKTRACE=${RUST_BACKTRACE} && cargo test --no-fail-fast --verbose
      env:
        RUST_LOG: ERROR
        RUST_BACKTRACE: full
        RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests --cfg tokio_unstable'
        RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests'