[package]
name = "databend-binaries"
description = "databend command line tools"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[features]
default = ["simd"]
memory-profiling = ["databend-meta/memory-profiling", "databend-query/memory-profiling", "common-base/memory-profiling"]
simd = ["databend-meta/simd", "databend-query/simd"]
tokio-console = [
    "databend-meta/tokio-console",
    "databend-query/io-uring",
    "common-base/tracing",
    "common-tracing/console",
]
io-uring = [
    "databend-meta/io-uring",
    "databend-query/io-uring",
    "common-meta-store/io-uring",
    "common-meta-sled-store/io-uring",
    "common-meta-raft-store/io-uring",
]

[dependencies]
# Workspace dependencies
common-base = { path = "../common/base" }
common-exception = { path = "../common/exception" }
common-grpc = { path = "../common/grpc" }
common-macros = { path = "../common/macros" }
common-meta-api = { path = "../meta/api" }
common-meta-app = { path = "../meta/app" }
common-meta-client = { path = "../meta/client" }
common-meta-embedded = { path = "../meta/embedded" }
common-meta-raft-store = { path = "../meta/raft-store" }
common-meta-sled-store = { path = "../meta/sled-store" }
common-meta-store = { path = "../meta/store" }
common-meta-types = { path = "../meta/types" }
common-metrics = { path = "../common/metrics" }
common-storage = { path = "../common/storage" }
common-tracing = { path = "../common/tracing" }
common-users = { path = "../query/users" }
databend-meta = { path = "../meta/service" }
databend-query = { path = "../query/service" }

# Crates.io dependencies
anyhow = "1.0.65"
clap = { version = "3.2.22", features = ["derive", "env"] }
openraft = { git = "https://github.com/drmingdrmer/openraft", tag = "v0.7.4-alpha.2" }
sentry = "0.27.0"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
tokio-stream = "0.1.10"
tonic = "0.8.1"
tracing = "0.1.36"
url = "2.3.1"

[[bin]]
name = "databend-meta"
path = "meta/main.rs"
doctest = false
test = false

[[bin]]
name = "databend-metabench"
path = "metabench/main.rs"
doctest = false
test = false

[[bin]]
name = "databend-metactl"
path = "metactl/main.rs"
doctest = false
test = false

[[bin]]
name = "databend-query"
path = "query/main.rs"
doctest = false
test = false
