[package]
name = "common-meta-embedded"
description = "distributed meta data service"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[features]
io-uring = ["common-meta-sled-store/io-uring", "common-meta-raft-store/io-uring"]

[dependencies]
# Workspace dependencies
common-base = { path = "../../common/base" }
common-exception = { path = "../../common/exception" }
common-meta-api = { path = "../api" }
common-meta-raft-store = { path = "../raft-store" }
common-meta-sled-store = { path = "../sled-store" }
common-meta-types = { path = "../types" }
common-tracing = { path = "../../common/tracing" }

# Crates.io dependencies
async-trait = "0.1.57"
once_cell = "1.15.0"
tempfile = "3.3.0"
tracing = "0.1.36"

[dev-dependencies]
anyhow = "1.0.65"
