[package]
name = "storages-common-table-meta"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }


[dependencies]
common-arrow = { path = "../../../../common/arrow" }
common-base = { path = "../../../../common/base" }
common-datavalues = { path = "../../../datavalues" }
common-exception = { path = "../../../../common/exception" }
common-expression = { path = "../../../expression" }

bincode = "1.3.3"
chrono = { workspace = true }
enum-as-inner = "0.5"
once_cell = "1.15.0"
serde = { workspace = true }
zstd = "0.12.3"
serde_json = "1.0.89"
snap = {version = "1.1.0",optional = true}
rmp-serde = {version = "1.1.1",optional = true}

[features]
dev = ["snap","rmp-serde"]
