name: 'Build Release'
description: 'Build with release profile'
inputs:
  github_token:
    description: "Github Token"
    required: true
  target:
    description: ""
    required: true
runs:
  using: "composite"
  steps:
    - name: Maximize build space
      uses: ./.github/actions/cleanup

    - uses: arduino/setup-protoc@v1
      if: "contains(inputs.target, 'apple')"
      with:
        version: '3.x'
        repo-token: ${{ inputs.github_token }}

    - shell: bash
      if: "contains(inputs.target, 'apple')"
      run: rustup target add ${{ inputs.target }}

    - shell: bash
      if: "contains(inputs.target, 'apple')"
      run: brew install thrift

    - name: Setup Build Tool
      if: "contains(inputs.target, 'linux')"
      uses: ./.github/actions/setup_build_tool
      with:
        image: multiarch

    # If you need to reset the cache version, increment the number after `v`
    - uses: Swatinem/rust-cache@v1
      with:
        sharedKey: release-${{ inputs.target }}-v2

    - shell: bash
      run: cargo build --release --target ${{ inputs.target }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-${{ github.sha }}-${{ inputs.target }}
        path: ./target/${{ inputs.target }}/release/databend-*

    # for cache
    - shell: bash
      run: cargo metadata --all-features --format-version 1 > ./target/metadata.json
