[package]
name = "common-tracing"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[features]
console = ["console-subscriber"]

[dependencies] # In alphabetical order
# Workspace dependencies
common-base = { path = "../base" }
common-exception = { path = "../exception" }

# Crates.io dependencies
console-subscriber = { version = "0.1.8", optional = true }
defer = "0.1"
fern = "0.6.2"
humantime = "2.1.0"
log = { workspace = true }
minitrace = { version = "0.4", features = ["enable"] }
minitrace-opentelemetry = "0.4"
opentelemetry = { version = "0.19.0", default-features = false, features = ["rt-tokio", "trace"] }
opentelemetry-jaeger = { version = "0.18.0", features = ["rt-tokio", "reqwest_blocking_collector_client"] }
sentry-tracing = "0.30.0"
serde = { workspace = true }
serde_json = "1"
tonic = { workspace = true }
tracing = { version = "0.1.36" }
tracing-appender = "0.2.2"
tracing-log = "0.1.3"
tracing-opentelemetry = "0.19.0"
tracing-subscriber = { version = "0.3.15", features = ["env-filter", "json", "valuable"] }
