[package]
name = "databend-common-tracing"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[features]
console = ["console-subscriber", "tracing", "tracing-subscriber"]

[dependencies] # In alphabetical order
# Workspace dependencies
databend-common-base = { path = "../base" }

# Crates.io dependencies
console-subscriber = { workspace = true, optional = true }
defer = "0.2"
fern = "0.6.2"
humantime = "2.1.0"
itertools = { workspace = true }
log = { workspace = true }
minitrace = { workspace = true }
minitrace-opentelemetry = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-otlp = { workspace = true }
opentelemetry_sdk = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true, optional = true }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true, optional = true }
