[package]
name = "databend-common-tracing"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
backtrace = { workspace = true }
chrono = { workspace = true }
color-backtrace = { version = "0.6" }
databend-common-base = { workspace = true }
databend-common-exception = { workspace = true }
defer = "0.2"
fastrace = { workspace = true }
fastrace-opentelemetry = { workspace = true }
itertools = { workspace = true }
libc = "0.2.153"
log = { workspace = true }
logforth = "0.11.2"
opentelemetry = { workspace = true }
opentelemetry-otlp = { workspace = true }
opentelemetry_sdk = { workspace = true }
serde = { workspace = true }
strip-ansi-escapes = "0.2"
tonic = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
