[package]
name = "common-tracing"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[features]
console = ["console-subscriber", "tracing", "tracing-subscriber"]

[dependencies] # In alphabetical order
# Workspace dependencies
common-base = { path = "../base" }

# Crates.io dependencies
console-subscriber = { version = "0.1.8", optional = true }
defer = "0.1"
fern = "0.6.2"
humantime = "2.1.0"
log = { workspace = true }
minitrace = { version = "0.4", features = ["enable"] }
minitrace-opentelemetry = "0.4"
opentelemetry = { version = "0.19", features = ["trace"] }
opentelemetry-jaeger = { version = "0.18", features = ["rt-tokio", "reqwest_blocking_collector_client"] }
serde = { workspace = true }
serde_json = "1"
tonic = { workspace = true }
tracing = { version = "0.1.36", optional = true }
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.15", features = ["env-filter", "json", "valuable"], optional = true }
