name: "Build Linux Hive"
description: "Build with hive on linux"
inputs:
  target:
    description: ""
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Build Tool
      uses: ./.github/actions/setup_build_tool
      with:
        target: ${{ inputs.target }}

    - name: Build Debug
      if: env.BUILD_PROFILE == 'debug'
      shell: bash
      run: cargo build --target ${{ inputs.target }} --features hive

    - name: Build Release
      if: env.BUILD_PROFILE == 'release'
      shell: bash
      run: cargo build --target ${{ inputs.target }} --features hive --release

    # - shell: bash
    #   run: readelf -p .comment ./target/${{ inputs.target }}/${{ env.BUILD_PROFILE }}/databend-query

    - name: Upload artifact
      uses: ./.github/actions/artifact_upload
      with:
        sha: ${{ github.sha }}
        target: ${{ inputs.target }}
        category: hive
