name: "Setup BendSQL"
description: "Setup BendSQL for CI"
runs:
  using: "composite"
  steps:
    - name: Download and Install
      shell: bash
      run: |
        sudo curl -L -o /etc/apt/sources.list.d/datafuselabs.sources https://repo.databend.rs/deb/datafuselabs.sources
        sudo apt update
        sudo apt install -y bendsql
        bendsql --version
