name: "Setup BendSQL"
description: "Setup BendSQL for CI"
runs:
  using: "composite"
  steps:
    - name: Download and Install
      shell: bash
      run: |
        sudo curl -L -o /usr/share/keyrings/datafuselabs-keyring.gpg https://repo.databend.rs/deb/datafuselabs.gpg
        sudo curl -L -o /etc/apt/sources.list.d/datafuselabs.list https://repo.databend.rs/deb/datafuselabs.list
        sudo apt update
        sudo apt install -y bendsql
        bendsql --version
