name: "Setup BendSQL"
description: "Setup BendSQL for CI"
runs:
  using: "composite"
  steps:
    - name: Download and Install
      shell: bash
      run: |
        curl -Lo /tmp/bendsql.deb https://github.com/datafuselabs/bendsql/releases/download/v0.9.3/bendsql_0.9.3_amd64.deb
        sudo dpkg -i /tmp/bendsql.deb
        bendsql --version
