[package]
name = "databend-common-base"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[features]
tracing = ["tokio/tracing"]
jemalloc = []
disable_initial_exec_tls = ["tikv-jemalloc-sys/disable_initial_exec_tls"]
memory-profiling = [
    "tikv-jemalloc-sys/stats",
    "tikv-jemalloc-sys/profiling",
    "tikv-jemalloc-sys/unprefixed_malloc_on_supported_platforms",
]

[dependencies]
async-backtrace = { workspace = true }
async-trait = { workspace = true }
borsh = { workspace = true }
bytesize = "1.1.0"
chrono = { workspace = true }
ctrlc = { version = "3.2.3", features = ["termination"] }
databend-common-exception = { workspace = true }
enquote = "1.1.0"
fastrace = { workspace = true }
futures = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
logcall = { workspace = true }
micromarshal = "0.5.0"
num-traits = "0.2.19"
num_cpus = "1.13.1"
once_cell = { workspace = true }
parking_lot = { workspace = true }
pin-project-lite = "0.2.9"
pprof = { version = "0.11.1", features = [
    "flamegraph",
    "protobuf-codec",
    "protobuf",
] }
prometheus-client = { workspace = true }
prometheus-parse = "0.2.3"
rand = { workspace = true, features = ["serde1"] }
regex = { workspace = true }
replace_with = "0.1.7"
reqwest = { workspace = true }
reqwest-hickory-resolver = { workspace = true }
rustix = "0.38.37"
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
state = "0.5"
tikv-jemalloc-ctl = { workspace = true }
tikv-jemalloc-sys = "0.5.2"
tokio = { workspace = true }
unicode-segmentation = "1.10.1"
uuid = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
procfs = { version = "^0.16" }

[dev-dependencies]
anyerror = { workspace = true }
anyhow = { workspace = true }
rand = { workspace = true }
serde_test = "1.0"

[build-dependencies]
databend-common-building = { workspace = true }

[lints]
workspace = true
