[package]
description = "Safe implementation of parquet IO, forked from parquet2."
edition = "2021"
license = "Apache-2.0"
name = "databend-common-parquet2"
version = "0.1.0"

[lib]
bench = false
name = "parquet2"

[dependencies]
async-stream = { workspace = true, optional = true }
brotli = { workspace = true, optional = true }
bytes = { workspace = true }
flate2 = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
lz4 = { workspace = true, optional = true }
opendal = { workspace = true }
parquet-format-safe = { workspace = true }
seq-macro = { workspace = true, default-features = false }
serde = { workspace = true, optional = true, features = ["derive"] }
snap = { workspace = true, optional = true }
streaming-decompression = { workspace = true }
xxhash-rust = { workspace = true, optional = true, features = ["xxh64"] }
zstd = { workspace = true, optional = true }

[dev-dependencies]
criterion = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }

[features]
async = ["async-stream", "futures", "parquet-format-safe/async"]
bloom_filter = ["xxhash-rust"]
default = ["snappy", "gzip", "lz4", "zstd", "brotli", "bloom_filter"]
full = ["snappy", "gzip", "lz4", "zstd", "brotli", "bloom_filter", "async"]
gzip = ["flate2/rust_backend"]
gzip_zlib_ng = ["flate2/zlib-ng"]
serde_types = ["serde"]
snappy = ["snap"]

[lints]
workspace = true
