[package]
name = "databend-functions-scalar-math"
version = "0.1.0"
edition = "2021"

[dependencies]
crc32fast = { workspace = true }
databend-common-base = { workspace = true }
databend-common-expression = { workspace = true }
ethnum = { workspace = true }
lexical-core = { workspace = true }
match-template = { workspace = true }
num-traits = { workspace = true }
strength_reduce = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["match-template"]