[package]
name = "databend-common-sharing"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
bytes = { workspace = true }
databend-common-auth = { path = "../../common/auth" }
databend-common-config = { path = "../config" }
databend-common-exception = { path = "../../common/exception" }
databend-common-meta-app = { path = "../../meta/app" }

async-backtrace = { workspace = true }
http = { workspace = true }
log = { workspace = true }
moka = "0.12"
opendal = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
