[package]
name = "common-sharing"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false

[dependencies]
anyhow = "1"
async-trait = "0.1"
bytes = "1"
futures = "0.3"
http = "0.2"
moka = "0.9"
opendal = "0.19"
reqwest = "0.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
