plugins:
  - remark-validate-links
  - [ remark-lint-no-dead-urls, {
      skipLocalhost: true,
      skipUrlPatterns: [/^https:\/\/(.*)github\.com/],
      gotOptions: {
        concurrency: 1,
        timeout: {
          lookup: 100,
          connect: 50,
          secureConnect: 50,
          socket: 1000,
          send: 5000,
          response: 1000
        }
      }
    }]
  # https://github.com/remarkjs/remark-lint/blob/main/doc/rules.md