[package]
name = "common-storages-preludes"
version = "0.1.0"
edition = "2021"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-arrow = { path = "../../../common/arrow" }
common-base = { path = "../../../common/base" }
common-catalog = { path = "../../catalog" }
common-config = { path = "../../config" }
common-contexts = { path = "../../../common/contexts" }
common-datablocks = { path = "../../datablocks" }
common-datavalues = { path = "../../datavalues" }
common-exception = { path = "../../../common/exception" }
common-functions = { path = "../../functions" }
common-grpc = { path = "../../../common/grpc" }
common-legacy-planners = { path = "../../legacy-planners" }
common-meta-app = { path = "../../../meta/app" }
common-meta-types = { path = "../../../meta/types" }
common-metrics = { path = "../../../common/metrics" }
common-pipeline-core = { path = "../../pipeline/core" }
common-pipeline-sinks = { path = "../../pipeline/sinks" }
common-pipeline-sources = { path = "../../pipeline/sources" }
common-pipeline-transforms = { path = "../../pipeline/transforms" }
common-storage = { path = "../../../common/storage" }
common-storages-util = { path = "../util" }
common-streams = { path = "../../streams" }
common-tracing = { path = "../../../common/tracing" }
common-users = { path = "../../users" }

thrift = { git = "https://github.com/datafuse-extras/thrift", tag = "v0.17.0" }

async-stream = "0.3.3"
async-trait = { version = "0.1.57", package = "async-trait-fn" }
chrono = "0.4.22"
clap = { version = "3.2.22", features = ["derive", "env"] }
futures = "0.3.24"
futures-util = "0.3.24"
itertools = "0.10.5"
num_cpus = "1.13.1"
once_cell = "1.15.0"
opendal = { version = "0.19", features = ["layers-retry"] }
parking_lot = "0.12.1"
reqwest = "0.11.12"
semver = "1.0.14"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
serde_repr = "0.1.9"
serfig = "0.0.2"
snailquote = "0.3.1"
time = "0.3.14"
tracing = "0.1.36"
typetag = "0.2.3"
uuid = { version = "1.1.2", features = ["serde", "v4"] }
walkdir = "2.3.2"

[build-dependencies]
common-building = { path = "../../../common/building" }
