[package]
name = "common-legacy-planners"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies] # In alphabetical order
# Workspace dependencies
common-datablocks = { path = "../datablocks" }
common-datavalues = { path = "../datavalues" }
common-exception = { path = "../../common/exception" }
common-functions = { path = "../functions" }
common-legacy-expression = { path = "../legacy-expression" }
common-meta-app = { path = "../../meta/app" }
common-meta-types = { path = "../../meta/types" }

# Github dependencies

# Crates.io dependencies
bitflags = "1.3.2"
once_cell = "1.15.0"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
typetag = "0.2.3"

[dev-dependencies]
pretty_assertions = "1.3.0"
