[package]
name = "common-storages-iceberg"
version = { workspace = true }
edition = "2021"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common-arrow = { path = "../../../common/arrow" }
common-catalog = { path = "../../catalog" }
common-exception = { path = "../../../common/exception" }
common-expression = { path = "../../expression" }
common-functions = { path = "../../functions" }
common-meta-app = { path = "../../../meta/app" }
common-meta-types = { path = "../../../meta/types" }
common-pipeline-core = { path = "../../pipeline/core" }
common-pipeline-sources = { path = "../../pipeline/sources" }
common-storage = { path = "../../../common/storage" }
common-storages-parquet = { path = "../parquet" }
storages-common-pruner = { path = "../common/pruner" }
storages-common-table-meta = { path = "../common/table-meta" }

arrow-schema = "45.0.0"
async-backtrace = { workspace = true }
async-trait = { version = "0.1.57", package = "async-trait-fn" }
chrono = { workspace = true }
futures = "0.3"
icelake = { version = "0.0.9" }
match-template = "0.0.1"
minitrace = { workspace = true }
opendal = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
typetag = "0.2"

[package.metadata.cargo-machete]
ignored = ["match-template"]
