[package]
name = "common-storages-iceberg"
version = { workspace = true }
edition = "2021"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common-arrow = { path = "../../../common/arrow" }
common-base = { path = "../../../common/base" }
common-catalog = { path = "../../catalog" }
common-exception = { path = "../../../common/exception" }
common-expression = { path = "../../expression" }
common-functions = { path = "../../functions" }
common-meta-app = { path = "../../../meta/app" }
common-meta-types = { path = "../../../meta/types" }
common-pipeline-core = { path = "../../pipeline/core" }
common-storage = { path = "../../../common/storage" }
common-storages-parquet = { path = "../parquet" }
storages-common-pruner = { path = "../common/pruner" }
storages-common-table-meta = { path = "../common/table_meta" }

arrow-schema = { workspace = true }
async-backtrace = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
icelake = "0.0.10"
match-template = { workspace = true }
minitrace = { workspace = true }
opendal = { workspace = true }
parquet = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
typetag = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["match-template"]
