[package]
name = "virtual-column"
description = "virtual column handler"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies]
# Workspace dependencies
common-base = { path = "../../../common/base" }
common-catalog = { path = "../../catalog" }
common-exception = { path = "../../../common/exception" }
common-meta-app = { path = "../../../meta/app" }
common-storages-fuse = { path = "../../storages/fuse" }
storages-common-table-meta = { path = "../../storages/common/table_meta" }

async-backtrace = { workspace = true }
async-trait = { workspace = true }

[build-dependencies]
