[package]
name = "databend-storages-common-blocks"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = true

[dependencies]
databend-common-exception = { path = "../../../../common/exception" }
databend-common-expression = { path = "../../../expression" }
databend-storages-common-table-meta = { path = "../table_meta" }
ethnum = { workspace = true }
parquet_rs = { workspace = true }

[build-dependencies]
