name: Bindings Python

on:
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/bindings.python.yml"
  workflow_call:
    inputs:
      tag:
        description: The tag to release
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  linux:
    name: ${{ matrix.target }}
    runs-on: [self-hosted, X64, Linux, 8c16g, gcp]
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/build_bindings_python
        with:
          target: ${{ matrix.target }}
          version: ${{ inputs.tag }}
      - name: Publish to PyPI
        if: inputs.tag
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_PASSWORD }}
        uses: PyO3/maturin-action@v1
        with:
          command: upload
          args: --skip-existing *
          working-directory: src/bendpy

  macos:
    if: inputs.tag
    name: ${{ matrix.target }}
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/build_bindings_python
        with:
          target: ${{ matrix.target }}
          version: ${{ inputs.tag }}
      - name: Publish to PyPI
        if: inputs.tag
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_PASSWORD }}
        uses: PyO3/maturin-action@v1
        with:
          command: upload
          args: --skip-existing *
          working-directory: src/bendpy
