name: Cargo
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt_and_clippy:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Rust setup
        run: |
          bash ./scripts/setup/dev_setup.sh

      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-clippycache-${{ secrets.CACHE_RESET_KEY }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-clippycache-${{ secrets.CACHE_RESET_KEY }}-
            ${{ runner.os }}-cargo-clippycache-
            ${{ runner.os }}-cargo-

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args:  --tests -- -D warnings
        env:
          CARGO_INCREMENTAL: '0'

      - name: Check formating
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
        env:
          CARGO_INCREMENTAL: '0'
