name: Cargo
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt_and_clippy:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Rust setup
        run: |
          bash ./scripts/setup/dev_setup.sh

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: Check formating
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
