name: Push Performance tools to Dockerhub
on:
  push:
    branches: master
    paths:
      - '**.rs'
      - '**.yaml'
      - '**.py'
      - '**Dockerfile'
jobs:
  build:
    runs-on: perf-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Perf Tool
        run: |
          export SCCACHE_DIR=/home/runner/.cache/sccache
          export RUSTC_WRAPPER=sccache
          make build-perf-tool
          sccache --show-stats

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_NAMESPACE }}/perf-tool:latest # assume latest tag is the latest release tag
          platforms: linux/amd64
          context: .
          file: ./docker/perf-tool/Dockerfile

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
