name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  publish_macos:
    name: Release macos assets
    runs-on: macos-11
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.REPO_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.REPO_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-2
      AWS_DEFAULT_OUTPUT: json
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Rust setup
        run: |
          bash ./scripts/setup/dev_setup.sh -yb
          rustup target add aarch64-apple-darwin
      - name: Build Binary
        run: |
          cargo build --release --target=${{ matrix.target }}
      - name: Pack binaries
        run: |
            brew install gnu-tar
            sudo /usr/sbin/purge
            gtar -C ./target/${{ matrix.target }}/release -czvf databend-${{ steps.get_version.outputs.VERSION }}-${{ matrix.target }}.tar.gz databend-query databend-meta
            gtar -C ./target/${{ matrix.target }}/release -czvf databend-tools-${{ steps.get_version.outputs.VERSION }}-${{ matrix.target }}.tar.gz databend-metactl
      - name: Publish Binaries
        uses: ./.github/actions/publish_binary
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ steps.get_version.outputs.VERSION }}
          target: ${{ matrix.target }}
          tag: ${{ github.ref }}
          aws_access_key_id: ${{ secrets.REPO_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.REPO_SECRET_ACCESS_KEY }}
          changelog: ${{ steps.changelog_reader.outputs.log_entry }}

  # NOTE: alpine build seems slow, we use cross only for musl now
  publish_linux_musl:
    name: Release linux musl assets
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.REPO_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.REPO_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-2
      AWS_DEFAULT_OUTPUT: json
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-unknown-linux-musl
          - x86_64-unknown-linux-musl
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Rust setup
        run: |
          cargo install --version 0.2.1 cross
      - name: Build Binary
        run: |
          RUSTFLAGS="-C link-arg=-Wl,--compress-debug-sections=zlib-gabi" cross build --release --target=${{ matrix.target }}
      - name: Pack binaries
        run: |
            tar -C ./target/${{ matrix.target }}/release -czvf databend-${{ steps.get_version.outputs.VERSION }}-${{ matrix.target }}.tar.gz databend-query databend-meta
            tar -C ./target/${{ matrix.target }}/release -czvf databend-tools-${{ steps.get_version.outputs.VERSION }}-${{ matrix.target }}.tar.gz databend-metactl
      - name: Publish Binaries
        uses: ./.github/actions/publish_binary
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ steps.get_version.outputs.VERSION }}
          target: ${{ matrix.target }}
          tag: ${{ github.ref }}
          aws_access_key_id: ${{ secrets.REPO_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.REPO_SECRET_ACCESS_KEY }}
          changelog: ${{ steps.changelog_reader.outputs.log_entry }}

  publish_linux_gnu:
    name: Release linux gnu assets
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.REPO_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.REPO_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-2
      AWS_DEFAULT_OUTPUT: json
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Setup Build Tool
        uses: ./.github/actions/setup_build_tool
        with:
          image: datafuselabs/build-tool:multiarch
      - name: get objcopy path
        id: get_objcopy
        shell: bash
        run: |
          OBJCOPY=/usr/bin/objcopy
          if [[ "${{ matrix.target }}" == "aarch64-unknown-linux-gnu" ]]; then
            OBJCOPY=/usr/bin/aarch64-linux-gnu-objcopy
          fi
          echo ::set-output name=OBJCOPY::${OBJCOPY}
      - name: Build Binary
        run: |
          cargo build --release --target=${{ matrix.target }}
          build-tool ${{ steps.get_objcopy.outputs.OBJCOPY }} --compress-debug-sections=zlib-gnu ./target/${{ matrix.target }}/release/databend-query
          build-tool ${{ steps.get_objcopy.outputs.OBJCOPY }} --compress-debug-sections=zlib-gnu ./target/${{ matrix.target }}/release/databend-meta
          build-tool ${{ steps.get_objcopy.outputs.OBJCOPY }} --compress-debug-sections=zlib-gnu ./target/${{ matrix.target }}/release/databend-metactl
      - name: Pack binaries
        run: |
          tar -C ./target/${{ matrix.target }}/release -czvf databend-${{ steps.get_version.outputs.VERSION }}-${{ matrix.target }}.tar.gz databend-query databend-meta
          tar -C ./target/${{ matrix.target }}/release -czvf databend-tools-${{ steps.get_version.outputs.VERSION }}-${{ matrix.target }}.tar.gz databend-metactl
      - name: Publish Binaries
        uses: ./.github/actions/publish_binary
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ steps.get_version.outputs.VERSION }}
          target: ${{ matrix.target }}
          tag: ${{ github.ref }}
          aws_access_key_id: ${{ secrets.REPO_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.REPO_SECRET_ACCESS_KEY }}
          changelog: ${{ steps.changelog_reader.outputs.log_entry }}

  release_docker_combined:
    name: Release combined docker image
    runs-on: ubuntu-latest
    needs: publish_linux_gnu
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download binaries for usage
        id: download_binaries
        run: |
          mkdir -p ./target/release
          wget https://repo.databend.rs/databend/${{ steps.get_version.outputs.VERSION }}/databend-${{ steps.get_version.outputs.VERSION }}-x86_64-unknown-linux-gnu.tar.gz
          tar xC ./target/release -f ./databend-${{ steps.get_version.outputs.VERSION }}-x86_64-unknown-linux-gnu.tar.gz

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_NAMESPACE }}/databend:${{ steps.get_version.outputs.VERSION }}
          platforms: linux/amd64
          context: .
          file: ./docker/Dockerfile
          build-args: VERSION=${{ steps.get_version.outputs.VERSION }}

  release_docker_separate:
    name: Release separate docker image for k8s service
    runs-on: ubuntu-latest
    needs: publish_linux_gnu
    strategy:
      fail-fast: false
      matrix:
        service:
          - meta
          - query
        distro:
          - debian
          - distroless
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download binaries for usage
        id: download_binaries
        run: |
          mkdir -p ./target/release
          wget https://repo.databend.rs/databend/${{ steps.get_version.outputs.VERSION }}/databend-${{ steps.get_version.outputs.VERSION }}-x86_64-unknown-linux-gnu.tar.gz
          wget https://repo.databend.rs/databend/${{ steps.get_version.outputs.VERSION }}/databend-${{ steps.get_version.outputs.VERSION }}-aarch64-unknown-linux-gnu.tar.gz
          mkdir -p ./target/x86_64-unknown-linux-gnu/release
          mkdir -p ./target/aarch64-unknown-linux-gnu/release
          tar xC ./target/x86_64-unknown-linux-gnu/release -f ./databend-${{ steps.get_version.outputs.VERSION }}-x86_64-unknown-linux-gnu.tar.gz
          tar xC ./target/aarch64-unknown-linux-gnu/release -f ./databend-${{ steps.get_version.outputs.VERSION }}-aarch64-unknown-linux-gnu.tar.gz
          mkdir -p ./distro/linux/amd64
          mkdir -p ./distro/linux/arm64
          cp ./target/x86_64-unknown-linux-gnu/release/databend-${{ matrix.service }} ./distro/linux/amd64
          cp ./target/aarch64-unknown-linux-gnu/release/databend-${{ matrix.service }} ./distro/linux/arm64

      - name: get image tags
        id: get_image_tags
        shell: bash
        run: |
          _base=${{ secrets.DOCKERHUB_NAMESPACE }}/databend-${{ matrix.service }}:${{ steps.get_version.outputs.VERSION }}
          _tags=${_base}-${{ matrix.distro }}
          if [[ "${{ matrix.service }}" == "debian" ]]; then
            _tags="${_tags}, ${_base}"
          fi
          echo ::set-output name=IMAGE_TAGS::${_tags}

      - name: push service image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.get_image_tags.outputs.IMAGE_TAGS }}
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./docker/${{ matrix.distro }}/${{ matrix.service }}.Dockerfile
          build-args: VERSION=${{ steps.get_version.outputs.VERSION }}
