name: Push Performance tools to Dockerhub
on:
  push:
    branches: main
    paths:
      - '**.rs'
      - '**.yaml'
      - '**.py'
      - '**Dockerfile'
jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          # Linux
          - { os: ubuntu-latest, toolchain: stable, target: x86_64-unknown-linux-gnu, cross: false }
          - { os: ubuntu-latest, toolchain: stable, target: aarch64-unknown-linux-gnu, cross: true }
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rust setup
        run: |
          bash ./scripts/setup/dev_setup.sh
          cargo install --version 0.1.16 cross

      - name: Build Perf Tool
        run: |
          if [ ${{ matrix.config.cross }} = true ]; then
              cross build --release --target=${{ matrix.config.target }} --bin databend-benchmark
          else
              cargo build --release --target=${{ matrix.config.target }} --bin databend-benchmark
          fi
          mkdir -p ./distro
          mv ./target/${{ matrix.config.target }}/release/databend-benchmark  ./distro

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_NAMESPACE }}/perf-tool:latest # assume latest tag is the latest release tag
          platforms: linux/amd64, linux/arm64
          context: .
          file: ./docker/perf-tool/Dockerfile

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }} && cat ./tests/perfs/perfs.yaml
