name: Dev

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "website/**"
      - "**.md"
      - "docker/**"
      - "scripts/setup/**"
      - ".devcontainer/**"
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  linux:
    uses: ./.github/workflows/reuse.linux.yml
    secrets: inherit
    with:
      build_profile: debug
      runner_provider: gcp

  linux_hive:
    uses: ./.github/workflows/reuse.linux.hive.yml
    secrets: inherit
    with:
      build_profile: debug
      runner_provider: gcp

  ready:
    runs-on: ubuntu-latest
    needs:
      - linux
      - linux_hive
    steps:
      - run: echo "ready"
