name: License checker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-license:
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check License Header
        uses: apache/skywalking-eyes@main
        with:
          log: info