name: macOS

on:
  workflow_call:
    inputs:
      build_profile:
        description: 'Build profile, debug or release'
        type: string
        required: true
        default: 'debug'

env:
  BUILD_PROFILE: ${{ inputs.build_profile }}

jobs:
  build_macos:
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all tags,  metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/build_macos
        with:
          target: ${{ matrix.target }}

  test_stateless_standalone_macos:
    runs-on: macos-latest
    needs: build_macos
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateless_standalone_macos

  test_stateless_cluster_macos:
    runs-on: macos-11
    needs: build_macos
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateless_cluster_macos
        timeout-minutes: 30

  sqllogic_standalone_macos:
    runs-on: macos-latest
    needs: build_macos
    strategy:
      matrix:
        dirs:
          - "base"
          - "ydb"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_sqllogic_standalone_macos
        timeout-minutes: 20
        with:
          dirs: ${{ matrix.dirs }}
