name: Linux

on:
  workflow_call:
    inputs:
      build_profile:
        description: 'Build profile, debug or release'
        type: string
        required: true
        default: 'debug'

env:
  BUILD_PROFILE: ${{ inputs.build_profile }}
  RUNNER_PROVIDER: aws

jobs:
  check:
    runs-on: [self-hosted, X64, Linux, 8c16g]
    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all tags, metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/check
        timeout-minutes: 30
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  license:
    runs-on: [self-hosted, X64, Linux, 4c8g]
    outputs:
      license: ${{ steps.license.outputs.license }}
    steps:
      - uses: actions/checkout@v3
      - name: Get License from S3
        id: license
        run: |
          aws s3 cp s3://databend-ci/misc/license.key license.key
          aws s3 cp s3://databend-ci/misc/license.json license.json
          echo "license=$(cat license.key | base64 -w 0)" >> $GITHUB_OUTPUT
          cat license.json

  build:
    name: build_${{ matrix.arch }}_${{ matrix.libc }}
    runs-on: [self-hosted, X64, Linux, 16c32g]
    strategy:
      matrix:
        include:
          - { arch: x86_64, libc: gnu }
    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all tags, metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/build_linux
        timeout-minutes: 30
        with:
          target: ${{ matrix.arch }}-unknown-linux-${{ matrix.libc }}
          artifacts: all

  build_other:
    name: build_${{ matrix.arch }}_${{ matrix.libc }}
    runs-on: [self-hosted, X64, Linux, 8c16g]
    strategy:
      matrix:
        include:
          - { arch: x86_64, libc: musl }
          - { arch: aarch64, libc: musl }
          - { arch: aarch64, libc: gnu }
    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all tags, metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/build_linux
        timeout-minutes: 30
        with:
          target: ${{ matrix.arch }}-unknown-linux-${{ matrix.libc }}
          artifacts: query

  test_unit:
    runs-on: [self-hosted, X64, Linux, 8c16g]
    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all tags, metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/test_unit
        timeout-minutes: 30

  test_metactl:
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_metactl
        timeout-minutes: 10

  test_meta-data-compat-openraft-07:
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_meta_data_compat_openraft_07
        timeout-minutes: 10

  test_compat:
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_compat
        timeout-minutes: 10

  test_compat_fuse:
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/fuse_compat
        timeout-minutes: 20

  test_meta_cluster:
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_meta_cluster
        timeout-minutes: 10

  sqllogic_management_mode:
    name: sqllogic_${{ matrix.dirs }}
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    strategy:
      matrix:
        dirs:
          - "management"
        handlers:
          - "mysql,http,clickhouse"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_sqllogic_management_mode_linux
        timeout-minutes: 10
        with:
          dirs: ${{ matrix.dirs }}
          handlers: ${{ matrix.handlers }}

  sqllogic_standalone:
    name: sqllogic_standalone_${{ matrix.dirs }}
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    strategy:
      matrix:
        dirs:
          - "query"
          - "standalone"
          - "crdb"
          - "duckdb"
          - "tpch"
        handlers:
          - "mysql,http,clickhouse"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_sqllogic_standalone_linux
        timeout-minutes: 15
        with:
          dirs: ${{ matrix.dirs }}
          handlers: ${{ matrix.handlers }}
          storage-format: all
      - name: Upload failure
        if: failure() || cancelled()
        uses: ./.github/actions/artifact_failure
        with:
          name: test-sqllogic-standalone-${{ matrix.handlers }}-${{ matrix.dirs }}

  sqllogic_standalone_with_native:
    name: sqllogic_standalone_${{ matrix.dirs }}_${{ matrix.format }}
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    strategy:
      matrix:
        dirs:
          - "base"
          - "ydb"
          - "tpcds"
        format:
          - "parquet"
          - "native"
        handlers:
          - "mysql,http,clickhouse"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_sqllogic_standalone_linux
        timeout-minutes: 15
        with:
          dirs: ${{ matrix.dirs }}
          handlers: ${{ matrix.handlers }}
          storage-format: ${{ matrix.format }}
      - name: Upload failure
        if: failure() || cancelled()
        uses: ./.github/actions/artifact_failure
        with:
          name: test-sqllogic-standalone-${{ matrix.handlers }}-${{ matrix.dirs }}_${{ matrix.format }}

  sqllogic_standalone_ee:
    name: sqllogic_standalone_${{ matrix.dirs }}_${{ matrix.format }}
    runs-on: [ self-hosted, X64, Linux, 4c8g ]
    if: needs.license.outputs.license
    needs: [build, license]
    strategy:
      matrix:
        dirs:
          - "ee"
        format:
          - "parquet"
        handlers:
          - "mysql,http,clickhouse"
    steps:
      - uses: actions/checkout@v3
      - name: Decode license
        id: license
        run: |
          echo "license=$(echo '${{ needs.license.outputs.license }}' | base64 -d)" >> $GITHUB_OUTPUT
      - uses: ./.github/actions/test_ee_sqllogic_standalone_linux
        timeout-minutes: 15
        env:
          QUERY_DATABEND_ENTERPRISE_LICENSE: ${{ steps.license.outputs.license }}
        with:
          dirs: ${{ matrix.dirs }}
          handlers: ${{ matrix.handlers }}
          storage-format: ${{ matrix.format }}
      - name: Upload failure
        if: failure() || cancelled()
        uses: ./.github/actions/artifact_failure
        with:
          name: test-ee-sqllogic-standalone-${{ matrix.handlers }}-${{ matrix.dirs }}_${{ matrix.format }}

  sqllogic_cluster:
    name: sqllogic_cluster_${{ matrix.dirs }}
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    strategy:
      matrix:
        dirs:
          - "base"
          - "query"
          - "cluster"
          - "crdb"
          - "duckdb"
          - "tpch"
        handlers:
          - "mysql,http,clickhouse"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_sqllogic_cluster_linux
        timeout-minutes: 15
        with:
          dirs: ${{ matrix.dirs }}
          handlers: ${{ matrix.handlers }}
      - name: Upload failure
        if: failure() || cancelled()
        uses: ./.github/actions/artifact_failure
        with:
          name: test-sqllogic-cluster-${{ matrix.handlers }}-${{ matrix.dirs }}

  sqllogic_cluster_large:
    name: sqllogic_cluster_${{ matrix.dirs }}
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    strategy:
      matrix:
        dirs:
          - "ydb"
          - "tpcds"
        handlers:
          - "mysql,http,clickhouse"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_sqllogic_cluster_linux
        timeout-minutes: 20
        with:
          dirs: ${{ matrix.dirs }}
          handlers: ${{ matrix.handlers }}
      - name: Upload failure
        if: failure() || cancelled()
        uses: ./.github/actions/artifact_failure
        with:
          name: test-sqllogic-cluster-${{ matrix.handlers }}-${{ matrix.dirs }}

  test_stateless_standalone:
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateless_standalone_linux
        timeout-minutes: 10

  test_stateless_cluster:
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateless_cluster_linux
        timeout-minutes: 10

  test_stateful_standalone:
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateful_standalone_linux
        timeout-minutes: 10
      - name: Upload failure
        if: failure() || cancelled()
        uses: ./.github/actions/artifact_failure
        with:
          name: test-stateful-standalone-linux

  test_stateful_sharing:
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateful_sharing
        if: env.BUILD_PROFILE == 'debug'
        timeout-minutes: 10
      - name: Upload failure
        if: failure() || cancelled()
        uses: ./.github/actions/artifact_failure
        with:
          name: test-stateful-sharing-linux

  test_stateful_cluster:
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateful_cluster_linux
        timeout-minutes: 10
      - name: Upload failure
        if: failure() || cancelled()
        uses: ./.github/actions/artifact_failure
        with:
          name: test-stateful-cluster-linux

  test_stateful_large_data:
    if: contains(github.event.pull_request.labels.*.name, 'ci-largedata')
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateful_large_data
        timeout-minutes: 60

  test_fuzz_standalone:
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_fuzz_standalone_linux
        timeout-minutes: 10
        continue-on-error: true

  test_ee_standalone:
    needs: [build, license]
    runs-on: [self-hosted, X64, Linux, 4c8g]
    if: needs.license.outputs.license
    steps:
      - uses: actions/checkout@v3
      - name: Decode license
        id: license
        run: |
          echo "license=$(echo '${{ needs.license.outputs.license }}' | base64 -d)" >> $GITHUB_OUTPUT
      - uses: ./.github/actions/test_ee_standalone_linux
        timeout-minutes: 10
        env:
          DATABEND_ENTERPRISE_LICENSE: ${{ steps.license.outputs.license }}
      - name: Upload failure
        if: failure() || cancelled()
        uses: ./.github/actions/artifact_failure
        with:
          name: test-stateful-standalone-linux
