name: Linux

on:
  workflow_call:
    inputs:
      build_profile:
        description: 'Build profile, debug or release'
        type: string
        required: true
        default: 'debug'
      runner_provider:
        description: 'Self-hosted runner provider, aws or gcp'
        type: string
        required: true
        default: 'aws'

env:
  BUILD_PROFILE: ${{ inputs.build_profile }}
  RUNNER_PROVIDER: ${{ inputs.runner_provider }}

jobs:
  check:
    runs-on: [self-hosted, X64, Linux, 16c32g, "${{ inputs.runner_provider }}"]
    steps:
      - uses: actions/checkout@v4
        with:
          # fetch all tags, metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/check
        timeout-minutes: 60
        with:
          github_token: ${{ github.token }}

  license:
    runs-on: [self-hosted, X64, Linux, 4c8g, "${{ inputs.runner_provider }}"]
    outputs:
      license: ${{ steps.license.outputs.license }}
    steps:
      - uses: actions/checkout@v4
      - name: Get License from S3
        if: inputs.runner_provider == 'aws'
        run: |
          aws s3 cp s3://databend-ci/misc/license.key license.key
          aws s3 cp s3://databend-ci/misc/license.json license.json
      - name: Get License from GCS
        if: inputs.runner_provider == 'gcp'
        run: |
          gcloud storage cp gs://databend-ci/misc/license.key license.key
          gcloud storage cp gs://databend-ci/misc/license.json license.json
      - name: Output License
        id: license
        run: |
          echo "license=$(cat license.key | base64 -w 0)" >> $GITHUB_OUTPUT
          cat license.json

  build:
    name: build_${{ matrix.arch }}_${{ matrix.libc }}
    runs-on: [self-hosted, X64, Linux, 16c32g, "${{ inputs.runner_provider }}"]
    strategy:
      matrix:
        include:
          - { arch: x86_64, libc: gnu }
    steps:
      - uses: actions/checkout@v4
        with:
          # fetch all tags, metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/build_linux
        timeout-minutes: 60
        with:
          sha: ${{ github.sha }}
          target: ${{ matrix.arch }}-unknown-linux-${{ matrix.libc }}
          artifacts: all

  build_address_sanitizer:
    name: build_${{ matrix.arch }}_${{ matrix.libc }}_asan
    runs-on: [ self-hosted, X64, Linux, 8c16g, "${{ inputs.runner_provider }}" ]
    strategy:
      matrix:
        include:
          - { arch: x86_64, libc: gnu }
          - { arch: aarch64, libc: gnu }
    steps:
      - uses: actions/checkout@v4
        with:
          # fetch all tags, metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/build_linux_sanitizer
        timeout-minutes: 60
        with:
          target: ${{ matrix.arch }}-unknown-linux-${{ matrix.libc }}
          artifacts: query

  build_other:
    name: build_${{ matrix.arch }}_${{ matrix.libc }}
    runs-on: [self-hosted, X64, Linux, 8c16g, "${{ inputs.runner_provider }}"]
    strategy:
      matrix:
        include:
          - { arch: x86_64, libc: musl }
          - { arch: aarch64, libc: musl }
          - { arch: aarch64, libc: gnu }
    steps:
      - uses: actions/checkout@v4
        with:
          # fetch all tags, metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/build_linux
        timeout-minutes: 60
        with:
          sha: ${{ github.sha }}
          target: ${{ matrix.arch }}-unknown-linux-${{ matrix.libc }}
          artifacts: query

  test_unit:
    runs-on: [self-hosted, X64, Linux, 16c32g, "${{ inputs.runner_provider }}"]
    steps:
      - uses: actions/checkout@v4
        with:
          # fetch all tags, metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/test_unit
        timeout-minutes: 60

  test_metactl:
    runs-on: [self-hosted, X64, Linux, 4c8g, "${{ inputs.runner_provider }}"]
    needs: [build, check]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test_metactl
        timeout-minutes: 10

  test_meta-data-compat-openraft-07:
    runs-on: [self-hosted, X64, Linux, 4c8g, "${{ inputs.runner_provider }}"]
    needs: [build, check]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test_meta_data_compat_openraft_07
        timeout-minutes: 10

  test_compat:
    runs-on: [self-hosted, X64, Linux, 4c8g, "${{ inputs.runner_provider }}"]
    needs: [build, check]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test_compat
        timeout-minutes: 10

  test_compat_fuse:
    runs-on: [self-hosted, X64, Linux, 4c8g, "${{ inputs.runner_provider }}"]
    needs: [build, check]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/fuse_compat
        timeout-minutes: 20

  test_meta_cluster:
    runs-on: [self-hosted, X64, Linux, 4c8g, "${{ inputs.runner_provider }}"]
    needs: [build, check]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test_meta_cluster
        timeout-minutes: 10

  sqllogic_management_mode:
    name: sqllogic_${{ matrix.dirs }}
    runs-on: [self-hosted, X64, Linux, 4c8g, "${{ inputs.runner_provider }}"]
    needs: [build, check]
    strategy:
      matrix:
        dirs:
          - "management"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test_sqllogic_management_mode_linux
        timeout-minutes: 10
        with:
          dirs: ${{ matrix.dirs }}
          handlers: mysql,http,clickhouse

  sqllogic_standalone:
    name: sqllogic_standalone_${{ matrix.dirs }}
    runs-on: [self-hosted, X64, Linux, 4c8g, "${{ inputs.runner_provider }}"]
    needs: [build, check]
    strategy:
      matrix:
        dirs:
          - "query"
          - "standalone"
          - "crdb"
          - "duckdb"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test_sqllogic_standalone_linux
        timeout-minutes: 15
        with:
          dirs: ${{ matrix.dirs }}
          handlers: mysql,http,clickhouse
          storage-format: all
      - name: Upload failure
        if: failure()
        uses: ./.github/actions/artifact_failure
        with:
          name: test-sqllogic-standalone-${{ matrix.dirs }}

  sqllogic_standalone_udf_server:
    name: sqllogic_standalone_${{ matrix.dirs }}
    runs-on: [self-hosted, X64, Linux, 4c8g, "${{ inputs.runner_provider }}"]
    needs: [build, check]
    strategy:
      matrix:
        dirs:
          - "udf_server"
    steps:
      - uses: actions/checkout@v3
      - name: Start UDF Server
        run: |
          pip install pyarrow
          python3 tests/udf-server/udf_test.py &
          sleep 2
      - uses: ./.github/actions/test_sqllogic_standalone_linux
        timeout-minutes: 15
        with:
          dirs: ${{ matrix.dirs }}
          handlers: mysql,http,clickhouse
          storage-format: all
      - name: Upload failure
        if: failure() || cancelled()
        uses: ./.github/actions/artifact_failure
        with:
          name: test-sqllogic-standalone-${{ matrix.dirs }}

  sqllogic_standalone_cloud:
    name: sqllogic_standalone_${{ matrix.dirs }}
    runs-on: [self-hosted, X64, Linux, 4c8g, "${{ inputs.runner_provider }}"]
    needs: [build, check]
    strategy:
      matrix:
        dirs:
          - "task"
    steps:
      - uses: actions/checkout@v3
      - name: Start Cloud Control Server
        run: |
          pip install grpcio grpcio-reflection protobuf grpcio-tools
          python3 tests/cloud_control_server/simple_server.py &
          sleep 2
      - uses: ./.github/actions/test_cloud_sqllogic_standalone_linux
        timeout-minutes: 15
        with:
          dirs: ${{ matrix.dirs }}
          handlers: mysql,http,clickhouse
          storage-format: all
      - name: Upload failure
        if: failure() || cancelled()
        uses: ./.github/actions/artifact_failure
        with:
          name: test-sqllogic-standalone-${{ matrix.dirs }}

  sqllogic_standalone_with_native:
    name: sqllogic_standalone_${{ matrix.dirs }}_${{ matrix.format }}
    runs-on: [self-hosted, X64, Linux, 4c8g, "${{ inputs.runner_provider }}"]
    needs: [build, check]
    strategy:
      matrix:
        dirs:
          - "base"
          - "ydb"
          - "tpcds"
          - "tpch"
        format:
          - "parquet"
          - "native"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test_sqllogic_standalone_linux
        timeout-minutes: 15
        with:
          dirs: ${{ matrix.dirs }}
          handlers: mysql,http,clickhouse
          storage-format: ${{ matrix.format }}
      - name: Upload failure
        if: failure()
        uses: ./.github/actions/artifact_failure
        with:
          name: test-sqllogic-standalone-${{ matrix.dirs }}_${{ matrix.format }}

  sqllogic_standalone_ee:
    name: sqllogic_standalone_${{ matrix.dirs }}_${{ matrix.format }}
    runs-on: [self-hosted, X64, Linux, 4c8g, "${{ inputs.runner_provider }}"]
    if: needs.license.outputs.license
    needs: [build, check, license]
    strategy:
      matrix:
        dirs:
          - "ee"
        format:
          - "parquet"
          - "native"
    steps:
      - uses: actions/checkout@v4
      - name: Decode license
        id: license
        run: |
          echo "license=$(echo '${{ needs.license.outputs.license }}' | base64 -d)" >> $GITHUB_OUTPUT
      - uses: ./.github/actions/test_ee_sqllogic_standalone_linux
        timeout-minutes: 15
        env:
          QUERY_DATABEND_ENTERPRISE_LICENSE: ${{ steps.license.outputs.license }}
        with:
          dirs: ${{ matrix.dirs }}
          handlers: mysql,http,clickhouse
          storage-format: ${{ matrix.format }}
      - name: Upload failure
        if: failure()
        uses: ./.github/actions/artifact_failure
        with:
          name: test-ee-sqllogic-standalone-${{ matrix.dirs }}_${{ matrix.format }}

  sqllogic_cluster:
    name: sqllogic_cluster_${{ matrix.dirs }}
    runs-on: [self-hosted, X64, Linux, 4c8g, "${{ inputs.runner_provider }}"]
    needs: [build, check]
    strategy:
      matrix:
        dirs:
          - "base"
          - "query"
          - "crdb"
          - "duckdb"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test_sqllogic_cluster_linux
        timeout-minutes: 15
        with:
          dirs: ${{ matrix.dirs }}
          handlers: mysql,http,clickhouse
      - name: Upload failure
        if: failure()
        uses: ./.github/actions/artifact_failure
        with:
          name: test-sqllogic-cluster-${{ matrix.dirs }}

  sqllogic_cluster_large:
    name: sqllogic_cluster_${{ matrix.dirs }}
    runs-on: [self-hosted, X64, Linux, 8c16g, "${{ inputs.runner_provider }}"]
    needs: [build, check]
    strategy:
      matrix:
        dirs:
          - "ydb"
          - "tpcds"
          - "tpch"
          - "cluster"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test_sqllogic_cluster_linux
        timeout-minutes: 20
        with:
          dirs: ${{ matrix.dirs }}
          handlers: http
      - name: Upload failure
        if: failure()
        uses: ./.github/actions/artifact_failure
        with:
          name: test-sqllogic-cluster-${{ matrix.dirs }}

  sqllogic_stage:
    name: sqllogic_${{ matrix.dirs }}_${{ matrix.storage }}
    runs-on: [self-hosted, X64, Linux, 4c8g, "${{ inputs.runner_provider }}"]
    needs: [build, check]
    strategy:
      matrix:
        dirs:
          - "stage"
          - "stage_parquet"
        storage:
          - "s3"
          - "fs"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test_sqllogic_stage
        timeout-minutes: 15
        with:
          storage: ${{ matrix.storage }}
          dirs: ${{ matrix.dirs }}
          handlers: mysql,http,clickhouse
      - name: Upload failure
        if: failure()
        uses: ./.github/actions/artifact_failure
        with:
          name: test-sqllogic-stage-${{ matrix.storage }}-${{ matrix.dirs }}

  test_stateless_standalone:
    runs-on: [self-hosted, X64, Linux, 4c8g, "${{ inputs.runner_provider }}"]
    needs: [build, check]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test_stateless_standalone_linux
        timeout-minutes: 10

  test_stateless_cluster:
    runs-on: [self-hosted, X64, Linux, 4c8g, "${{ inputs.runner_provider }}"]
    needs: [build, check]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test_stateless_cluster_linux
        timeout-minutes: 10

  test_stateful_standalone:
    runs-on: [self-hosted, X64, Linux, 4c8g, "${{ inputs.runner_provider }}"]
    needs: [build, check]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test_stateful_standalone_linux
        timeout-minutes: 10
      - name: Upload failure
        if: failure()
        uses: ./.github/actions/artifact_failure
        with:
          name: test-stateful-standalone-linux

  test_stateful_sharing:
    runs-on: [self-hosted, X64, Linux, 4c8g, "${{ inputs.runner_provider }}"]
    needs: [build, check]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test_stateful_sharing
        if: env.BUILD_PROFILE == 'debug'
        timeout-minutes: 10
      - name: Upload failure
        if: failure()
        uses: ./.github/actions/artifact_failure
        with:
          name: test-stateful-sharing-linux

  test_stateful_cluster:
    runs-on: [self-hosted, X64, Linux, 4c8g, "${{ inputs.runner_provider }}"]
    needs: [build, check]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test_stateful_cluster_linux
        timeout-minutes: 15
      - name: Upload failure
        if: failure()
        uses: ./.github/actions/artifact_failure
        with:
          name: test-stateful-cluster-linux

  test_stateful_large_data:
    if: contains(github.event.pull_request.labels.*.name, 'ci-largedata')
    runs-on: [self-hosted, X64, Linux, 4c8g, "${{ inputs.runner_provider }}"]
    needs: [build, check]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test_stateful_large_data
        timeout-minutes: 60

  test_fuzz_standalone:
    runs-on: [self-hosted, X64, Linux, 4c8g, "${{ inputs.runner_provider }}"]
    needs: [build, check]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test_fuzz_standalone_linux
        timeout-minutes: 10
        continue-on-error: true

  test_ee_standalone:
    needs: [build, check, license]
    runs-on: [self-hosted, X64, Linux, 4c8g, "${{ inputs.runner_provider }}"]
    if: needs.license.outputs.license
    steps:
      - uses: actions/checkout@v4
      - name: Decode license
        id: license
        run: |
          echo "license=$(echo '${{ needs.license.outputs.license }}' | base64 -d)" >> $GITHUB_OUTPUT
      - uses: ./.github/actions/test_ee_standalone_linux
        timeout-minutes: 10
        env:
          DATABEND_ENTERPRISE_LICENSE: ${{ steps.license.outputs.license }}
      - name: Upload failure
        if: failure()
        uses: ./.github/actions/artifact_failure
        with:
          name: test-stateful-standalone-linux

  test_ee_standalone_background:
    needs: [build, check, license]
    runs-on: [self-hosted, X64, Linux, 4c8g, "${{ inputs.runner_provider }}"]
    if: needs.license.outputs.license
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup_bendsql
      - name: Decode license
        id: license
        run: |
          echo "license=$(echo '${{ needs.license.outputs.license }}' | base64 -d)" >> $GITHUB_OUTPUT
      - uses: ./.github/actions/test_ee_standalone_background_linux
        timeout-minutes: 10
        env:
          DATABEND_ENTERPRISE_LICENSE: ${{ steps.license.outputs.license }}
          QUERY_DATABEND_ENTERPRISE_LICENSE: ${{ steps.license.outputs.license }}
      - name: Upload failure
        if: failure()
        uses: ./.github/actions/artifact_failure
        with:
          name: test-stateful-standalone-linux
