name: macOS

on:
  workflow_call:
    inputs:
      build_profile:
        description: 'Build profile, debug or release'
        type: string
        required: true
        default: 'debug'

env:
  BUILD_PROFILE: ${{ inputs.build_profile }}
  RUNNER_PROVIDER: github

jobs:
  build:
    name: build_${{ matrix.arch }}
    runs-on: macos-11
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all tags,  metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/build_macos
        with:
          target: ${{ matrix.arch }}-apple-darwin

  test_stateless_standalone_macos:
    runs-on: macos-11
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateless_standalone_macos

  test_stateless_cluster_macos:
    runs-on: macos-11
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateless_cluster_macos
        timeout-minutes: 30

  sqllogic_standalone_macos:
    runs-on: macos-11
    needs: build
    strategy:
      matrix:
        dirs:
          - "base"
          - "ydb"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_sqllogic_standalone_macos
        timeout-minutes: 20
        with:
          dirs: ${{ matrix.dirs }}
