name: Stateless(Cluster)
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Rust setup
        run: |
          bash ./scripts/setup/dev_setup.sh

      - name: Build
        run: cargo build --verbose

      - name: Run Stateless Tests with Cluster mode
        run: |
          bash ./scripts/ci/ci-stateless-tests-cluster.sh
