name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          curl -i -X POST \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          --data '{"event": "COMMENT", "body": "Hello, world!\n"}' \
          --fail \
          "https://api.github.com/repos/datafuselabs/databend/pulls/2068/reviews"