name: Welcome
on: [pull_request, issues]

jobs:
  first-interaction:
    name: "WelcomeBot 🦖"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '## 🎉 Thank you for opening an issue! 🎉  One of the maintainers of the project will respond as soon as possible. Seeing that you are new here, please familiarize yourself with our [code of conduct](https://github.com/datafuselabs/datafuse/blob/master/website/datafuse/docs/policies/code-of-conduct.md) and [contributing to datafuse](https://github.com/datafuselabs/datafuse/blob/master/website/datafuse/docs/development/contributing.md)'
          pr-message: '## 🎉 Welcome to Contribute! 🎉  One of the maintainers of the project will respond here as soon as possible. Seeing that you are new here, please familiarize yourself with our [code of conduct](https://github.com/datafuselabs/datafuse/blob/master/website/datafuse/docs/policies/code-of-conduct.md) [contributing to datafuse](https://github.com/datafuselabs/datafuse/blob/master/website/datafuse/docs/development/contributing.md)'