[package]
name = "common-procedures"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Workspace dependencies
common-exception = { path = "../../common/exception" }
common-expression = { path = "../expression" }
common-meta-app = { path = "../../meta/app" }
common-storages-fuse = { path = "../storages/fuse" }
common-storages-system = { path = "../storages/system" }
# GitHub dependencies

# Crates.io dependencies
once_cell = "1.15.0"
